package rollcall

import (
	"archive/zip"
	"bytes"
	"fmt"
	"time"
)

// TemplateFileName is the archive the vendor's Control Panel reads before it
// draws anything.
//
// The name is fixed and upper case. A Control Panel pointed at a device that
// does not serve it shows nothing at all — not an empty device, nothing — so a
// provider that means to be usable from the vendor's own tool has to have one,
// even if what is inside is only a description of the menu.
const TemplateFileName = "TEMPLATE.ZIP"

// templateEntryName is the description inside the archive.
const templateEntryName = "template.txt"

// templateEpoch is the timestamp every entry carries.
//
// A fixed one rather than the clock, because the archive is generated from the
// tree and two providers serving the same tree should serve the same bytes: a
// client caching by checksum would otherwise re-fetch it on every restart.
var templateEpoch = time.Date(2000, time.January, 1, 0, 0, 0, 0, time.UTC)

// buildTemplate renders the served model as an archive.
//
// What is inside is ours rather than the vendor's binary layout, which is not
// documented anywhere we have: it describes the same thing in a form a person
// can read. A Control Panel gets an archive where it demands one and can draw
// the device from the menu service, which is what it does with the menu anyway;
// anything that wants to know what a card offers without walking it has this.
func buildTemplate(m *model) []byte {
	var body bytes.Buffer

	fmt.Fprintf(&body, "# %s\n", m.frame.Name)
	fmt.Fprintf(&body, "# generated by dhs; describes what the menu service serves\n\n")

	for _, n := range m.portNumbers() {
		prt := m.port(n)
		fmt.Fprintf(&body, "[port %02X] %s\n", n, prt.id.Name)
		for _, l := range prt.menu(true) {
			if l.Command == 0 {
				fmt.Fprintf(&body, "  %d\t%s\tcontainer span=%d\n", l.Index, l.Text, l.Step)
				continue
			}
			fmt.Fprintf(&body, "  %d\t%s\tcmd=%d style=%s range=%d..%d div=%d %s\n",
				l.Index, l.Text, l.Command, l.Style, l.MinRange, l.MaxRange, l.Scale(), l.Param)
		}
		body.WriteString("\n")
	}

	var out bytes.Buffer
	zw := zip.NewWriter(&out)

	// Nothing here can fail: the destination is a buffer in memory, and the
	// header is one we build ourselves. The errors are discarded rather than
	// handled because handling them would mean a branch no test can reach.
	w, _ := zw.CreateHeader(&zip.FileHeader{
		Name:     templateEntryName,
		Method:   zip.Deflate,
		Modified: templateEpoch,
	})
	_, _ = w.Write(body.Bytes())
	_ = zw.Close()

	return out.Bytes()
}
