package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"time"

	"acp/internal/diff"
	"acp/internal/export/canonical"
)

// runDiff drives `acp diff <before> <after>` — issue #49. Compares two
// canonical tree.json files and emits either a human text report or a
// Keep-a-Changelog markdown block; with --into <path> the markdown is
// prepended to the named CHANGELOG.md (creating it if absent).
func runDiff(ctx context.Context, args []string) error {
	fs := flag.NewFlagSet("diff", flag.ExitOnError)
	format := fs.String("format", "text", "output format: text | changelog")
	version := fs.String("version", "", "version label for changelog entry (e.g. 2.4)")
	date := fs.String("date", "", "date for changelog entry (YYYY-MM-DD). Default: today UTC.")
	into := fs.String("into", "",
		"when --format=changelog, prepend the new section to this CHANGELOG.md file (creates if absent)")

	if err := fs.Parse(args); err != nil {
		return err
	}
	rest := fs.Args()
	if len(rest) != 2 {
		return fmt.Errorf("usage: acp diff <before-tree.json> <after-tree.json> [--format text|changelog] [--version V] [--date D] [--into PATH]")
	}

	before, err := loadCanonicalExport(rest[0])
	if err != nil {
		return fmt.Errorf("load before: %w", err)
	}
	after, err := loadCanonicalExport(rest[1])
	if err != nil {
		return fmt.Errorf("load after: %w", err)
	}

	report := diff.Diff(before, after)

	switch *format {
	case "text":
		return report.WriteText(os.Stdout)
	case "changelog":
		if *version == "" {
			return fmt.Errorf("--version is required when --format=changelog")
		}
		dateStr := *date
		if dateStr == "" {
			dateStr = time.Now().UTC().Format("2006-01-02")
		}
		if *into == "" {
			return report.WriteChangelog(os.Stdout, *version, dateStr)
		}
		return prependChangelog(*into, report, *version, dateStr)
	}
	return fmt.Errorf("unknown --format %q (want text or changelog)", *format)
}

// loadCanonicalExport reads and unmarshals a canonical tree.json file.
func loadCanonicalExport(path string) (*canonical.Export, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()

	data, err := io.ReadAll(f)
	if err != nil {
		return nil, err
	}

	var x canonical.Export
	if err := json.Unmarshal(data, &x); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	return &x, nil
}

// prependChangelog inserts the new version section at the top of the
// named CHANGELOG.md file, directly under the file's H1 header if any.
// Creates the file with a fresh H1 banner when it doesn't exist yet.
// Written atomically via temp + rename so a crash can't corrupt an
// existing CHANGELOG.
func prependChangelog(path string, report *diff.Report, version, date string) error {
	var buf bytesBuffer
	if err := report.WriteChangelog(&buf, version, date); err != nil {
		return fmt.Errorf("render changelog block: %w", err)
	}
	newSection := buf.String()

	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", path, err)
	}

	var out string
	if len(existing) == 0 {
		// Fresh CHANGELOG — give it a small preamble so future human
		// edits have context.
		out = fmt.Sprintf("# DM changelog\n\nGenerated by `acp diff`. Do not hand-edit version sections.\n\n%s",
			newSection)
	} else {
		out = insertAfterH1(string(existing), newSection)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(out), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("rename %s → %s: %w", tmp, path, err)
	}
	fmt.Printf("prepended [%s] — %s section to %s\n", version, date, path)
	return nil
}

// insertAfterH1 drops `block` immediately after the file's first
// H1 line + any preamble paragraphs before the first "## " heading.
// If the file has no H1, block is prepended.
func insertAfterH1(existing, block string) string {
	// Find the first "## " line (next version section) and insert
	// `block` just before it. If none exists, append at end.
	nextH2 := indexOfLine(existing, "## ")
	if nextH2 < 0 {
		// No previous version sections — append block at file end
		// after ensuring a trailing blank line.
		sep := ""
		if len(existing) > 0 && existing[len(existing)-1] != '\n' {
			sep = "\n"
		}
		return existing + sep + "\n" + block
	}
	return existing[:nextH2] + block + existing[nextH2:]
}

// indexOfLine finds the byte offset of the first line that starts
// with `prefix` (used to locate the first "## " heading in a
// CHANGELOG). Returns -1 if no such line exists.
func indexOfLine(s, prefix string) int {
	// Walk line boundaries.
	start := 0
	for start < len(s) {
		end := start
		for end < len(s) && s[end] != '\n' {
			end++
		}
		if end-start >= len(prefix) && s[start:start+len(prefix)] == prefix {
			return start
		}
		if end >= len(s) {
			break
		}
		start = end + 1
	}
	return -1
}

// bytesBuffer is a tiny local alias to sidestep the bytes import for
// this one call site (keeps the file's imports minimal).
type bytesBuffer struct {
	b []byte
}

func (bb *bytesBuffer) Write(p []byte) (int, error) {
	bb.b = append(bb.b, p...)
	return len(p), nil
}
func (bb *bytesBuffer) String() string { return string(bb.b) }
