// Code generated from "RRCS Interface Specification" 9.0.1 Rev 1, §8.10.4,
// by reading its property tables in reading order. DO NOT EDIT by hand:
// correct the reading and regenerate.
//
// Where the specification abbreviates a list of named values with dots,
// only the values it prints are here.

package main

// rrcsSpecProp is what the specification prints about one property: its
// type, its default, its range, its longest text, its named values.
type rrcsSpecProp struct {
	Type, Default, Min, Max, MaxLen, Enum string
}

// rrcsSpecMeta is keyed by object type, then by the struct the property
// sits in ("" for the object itself), then by property name.
var rrcsSpecMeta = map[string]map[string]map[string]rrcsSpecProp{
	"auto-listen-off-cmd": {
		"": {
			"ForceFail": {"bool", "true", "", "", "", ""},
		},
	},
	"beep-panel-cmd": {
		"": {
			"ForceFail": {"bool", "true", "", "", "", ""},
		},
	},
	"call-to-conference": {
		"": {
			"AllowChangingDestConf": {"bool", "false", "", "", "", ""},
			"AllowSelectingConf":    {"bool", "false", "", "", "", ""},
			"AudioPriority":         {"int", "1", "", "", "", ""},
			"Conference":            {"int", "", "", "", "", ""},
			"ForceFail":             {"bool", "true", "", "", "", ""},
			"Listen":                {"bool", "true", "", "", "", ""},
			"Owner":                 {"int", "", "", "", "", ""},
			"Talk":                  {"bool", "true", "", "", "", ""},
			"UseSecondChannel":      {"bool", "false", "", "", "", ""},
		},
	},
	"call-to-group": {
		"": {
			"AudioPriority":             {"int", "1", "", "", "", ""},
			"DisableDestinVolumeAdjust": {"bool", "false", "", "", "", ""},
			"ForceFail":                 {"bool", "true", "", "", "", ""},
			"Group":                     {"int", "", "", "", "", ""},
			"Owner":                     {"int", "", "", "", "", ""},
			"ShowIncomingMarker":        {"bool", "false", "", "", "", ""},
			"UseSecondChannel":          {"bool", "false", "", "", "", ""},
		},
	},
	"call-to-ifb": {
		"": {
			"ForceFail":         {"bool", "true", "", "", "", ""},
			"IFBObjectID":       {"int", "", "", "", "", ""},
			"Monitoring":        {"int", "0", "", "", "", "0=Switchable|1=Always On|2=Always Off"},
			"TrunkingIFBNumber": {"int", "", "", "", "", ""},
			"TrunkingNetAddr":   {"int", "", "", "", "", ""},
			"UseSecondChannel":  {"bool", "false", "", "", "", ""},
		},
	},
	"call-to-port-cmd": {
		"": {
			"AllowDialpad":                 {"bool", "false", "", "", "", ""},
			"AllowFixedNumber":             {"bool", "false", "", "", "", ""},
			"AllowPhonebook":               {"bool", "false", "", "", "", ""},
			"AllowSetInOutGain":            {"bool", "true", "", "", "", ""},
			"AllowTelephoneCall":           {"bool", "false", "", "", "", ""},
			"AutolistenFromDest":           {"bool", "false", "", "", "", ""},
			"BeepDestOnCall":               {"bool", "false", "", "", "", ""},
			"DestinationUsesSecondChannel": {"bool", "false", "", "", "", ""},
			"DisableCrosspointVolume":      {"bool", "false", "", "", "", ""},
			"DuplexCall":                   {"bool", "false", "", "", "", ""},
			"FixedNumber":                  {"string", "", "", "", "", ""},
			"ForceFail":                    {"bool", "true", "", "", "", ""},
			"Isolate":                      {"bool", "false", "", "", "", ""},
			"IsolateSelf":                  {"bool", "false", "", "", "", ""},
			"Monitoring":                   {"int", "0", "", "", "", "0=Switchable|1=Always On|2=Always Off"},
			"Priority":                     {"int", "1", "", "", "", ""},
			"SourceUsesSecondChannel":      {"bool", "false", "", "", "", ""},
			"TrunkcallPriority":            {"int", "1", "", "", "", ""},
			"TrunkingNetAddr":              {"int", "", "", "", "", ""},
			"TrunkingPortAddr":             {"int", "", "", "", "", ""},
		},
	},
	"client-card": {
		"": {
			"LongName":   {"string", "", "", "", "32", ""},
			"Node":       {"int", "", "", "", "", ""},
			"NodeTarget": {"int", "", "", "", "", ""},
			"Slot":       {"int", "", "", "", "", ""},
			"SlotTarget": {"int", "", "", "", "", ""},
			"SwapForced": {"bool", "", "", "", "", ""},
		},
		"Aes67": {
			"DefaultGateway":      {"ip", "", "", "", "", ""},
			"IGMPVersion":         {"int", "", "0", "1", "", ""},
			"IpAddress":           {"ip", "", "", "", "", ""},
			"MediaInterface":      {"int", "", "", "", "", "1=Interface 1 -> default|2=Interface 2"},
			"Network":             {"string", "", "", "", "", ""},
			"NetworkSpeed":        {"int", "", "", "", "", ""},
			"PTP":                 {"int", "", "0", "127", "", ""},
			"PtpAnnounceInterval": {"int", "", "-3", "4", "", ""},
			"PtpMode":             {"int", "", "", "", "", "0=Multicast|1=Hybrid"},
			"PtpPriority":         {"int", "", "0", "255", "", ""},
			"PtpPriority2":        {"int", "", "0", "255", "", ""},
			"ServiceCodePoint":    {"int", "", "0", "63", "", ""},
			"TcpUdpPort":          {"int", "", "1024", "65535", "", ""},
		},
		"Dante": {
			"DanteDeviceName": {"string", "", "", "", "", ""},
		},
		"Discovery": {
			"MulticastIp": {"ip", "", "", "", "", ""},
			"Port":        {"int", "", "0", "65535", "", ""},
		},
		"Dns": {
			"DnsSuffix":          {"string", "", "", "", "", ""},
			"PrimaryDnsServer":   {"ip", "", "", "", "", ""},
			"SecondaryDnsServer": {"ip", "", "", "", "", ""},
		},
		"Madi": {
			"Channels":      {"int", "", "", "", "", "0=01 - 08|1=09 - 16|2=17 - 24|3=25 - 32|4=33 - 40|5=41 - 48|6=49 - 56|7=57 -64 (need FrameLengt = 1)"},
			"DownInterface": {"int", "", "", "", "", "0=Optical|1=Electrical"},
			"FrameLength":   {"int", "", "", "", "", "0=56 Channels|1=64 Channels"},
			"MadiInterface": {"int", "", "", "", "", "0=Interface 1 -> default|1=Interface 2"},
			"Smux":          {"int", "", "", "", "", "0=Disabled|1=Enabled"},
			"SyncSource":    {"int", "", "", "", "", "0=Internal Clock"},
			"UpInterface":   {"int", "", "", "", "", "0=Optical|1=Electrical"},
		},
		"Media": {
			"DefaultGateway":        {"ip", "", "1024", "65535", "", ""},
			"IGMPVersion":           {"int", "", "0", "1", "", ""},
			"IpAddress":             {"ip", "", "", "", "", ""},
			"Network":               {"string", "", "", "", "", ""},
			"NetworkSpeed":          {"int", "", "", "", "", ""},
			"ObtainIpAddrAutomatic": {"bool", "", "", "", "", ""},
		},
		"Nmos": {
			"Enable":                 {"bool", "", "", "", "", "1=NMOS API Version 1.1|2=NMOS API Version 1.2|3=NMOS API Version 1.3"},
			"LocalPort":              {"int", "", "1024", "65535", "", ""},
			"NetworkInterface":       {"int", "", "", "", "", "0=Media_1|1=Media_2|2=Config"},
			"RegistrationApiVersion": {"int", "", "", "", "", "1=NMOS API Version 1.1|2=NMOS API Version 1.2|3=NMOS API Version 1.3"},
			"RegistrationIp":         {"ip", "", "", "", "", ""},
			"RegistrationMode":       {"int", "", "", "", "", "0=Automatic|1=Peer2Peer|2=Manual"},
			"RegistrationPort":       {"int", "", "1", "65535", "", ""},
		},
		"Ptp": {
			"PTP":                 {"int", "", "0", "127", "", ""},
			"PtpAnnounceInterval": {"int", "", "-3", "4", "", ""},
			"PtpMode":             {"int", "", "", "", "", "0=Multicast|1=Hybrid"},
			"PtpPriority":         {"int", "", "0", "255", "", ""},
			"PtpPriority2":        {"int", "", "0", "255", "", ""},
		},
		"VoIP": {
			"DefaultGateway":         {"ip", "", "", "", "", ""},
			"DnsHostName":            {"string", "", "", "", "", ""},
			"IpAddress":              {"ip", "", "", "", "", ""},
			"NetMask":                {"string", "", "", "", "", ""},
			"ObtainDnsAddrAutomatic": {"bool", "", "", "", "", ""},
			"ObtainIpAddrAutomatic":  {"bool", "", "", "", "", ""},
			"PrimaryDnsServer":       {"ip", "", "", "", "", ""},
			"SecondaryDnsServer":     {"ip", "", "", "", "", ""},
			"ServiceCodePoint":       {"int", "", "", "", "", "1=Autonegotiation|2=10 Mbit Half|3=10 Mbit Full|4=100 Mbit Half|5=100 Mbit Full"},
			"TcpUdpPort":             {"int", "", "", "", "", ""},
		},
	},
	"clone-output-port-cmd": {
		"": {
			"ClonedOutputSecondChannel":  {"bool", "false", "", "", "", ""},
			"ForceFail":                  {"bool", "true", "", "", "", ""},
			"OutputToCloneSecondChannel": {"bool", "false", "", "", "", ""},
		},
	},
	"conference": {
		"": {
			"Alias":          {"string", "", "", "", "8", ""},
			"IsTrunkEnabled": {"bool", "", "", "", "", ""},
			"Label":          {"string", "", "", "", "8", ""},
			"LongName":       {"string", "", "", "", "32", ""},
			"ObjectID":       {"int", "", "", "", "", ""},
			"TrunkingAddr":   {"int", "", "", "", "", ""},
		},
	},
	"control-audiopatch-cmd": {
		"": {
			"AudiopatchElement": {"int", "", "", "", "", ""},
			"ForceFail":         {"bool", "true", "", "", "", ""},
		},
	},
	"device": {
		"": {
			"DeviceType":  {"int", "", "", "", "", "0=Connect VoIP|1=NSA-003A|2=NSA-004A|3=NSA-005A|4=NSA-006A|5=NSA-007A|6=NSA-010C|7=NSA-008A|8=PunQtum"},
			"LongName":    {"string", "", "", "", "32", ""},
			"NewLongName": {"string", "", "", "", "32", ""},
		},
		"AssignedGPIOs": {
			"AddToDevice":   {"bool", "", "", "", "", ""},
			"InputChannel":  {"int", "", "", "", "", ""},
			"OutputChannel": {"int", "", "", "", "", ""},
		},
		"AssignedPorts": {
			"AddToDevice":      {"bool", "", "", "", "", ""},
			"ChannelSelection": {"int", "", "", "", "", ""},
			"InputChannel":     {"int", "", "", "", "", ""},
			"OutputChannel":    {"int", "", "", "", "", ""},
		},
		"DeviceConnectVoIP": {
			"ChannelNumber":    {"int", "", "", "", "", ""},
			"IpAddress":        {"string", "", "", "", "", ""},
			"IpAddressMedia1":  {"string", "", "", "", "", ""},
			"IpAddressMedia2":  {"string", "", "", "", "", ""},
			"IpPort":           {"int", "", "", "", "", ""},
			"IpPortMedia1":     {"int", "", "", "", "", ""},
			"IpPortMedia2":     {"int", "", "", "", "", ""},
			"MulticastIpIn":    {"string", "", "", "", "", ""},
			"MulticastIpOut":   {"string", "", "", "", "", ""},
			"MulticastPortIn":  {"int", "", "", "", "", ""},
			"MulticastPortOut": {"int", "", "", "", "", ""},
			"PlayMode":         {"int", "", "", "", "", "0=Synton|1=Synchron"},
			"PtpRole":          {"int", "", "", "", "", ""},
			"ReceiveBuffer":    {"int", "", "", "", "", ""},
			"WebUIIpAddress":   {"string", "", "", "", "", ""},
		},
		"DevicePunQtum": {
			"PlayMode":       {"int", "", "", "", "", "0=Synton|1=Synchron"},
			"PunQtumPatchId": {"int", "", "", "", "", ""},
		},
	},
	"dim-level-command": {
		"": {
			"DestinationUsesSecondChannel": {"bool", "false", "", "", "", ""},
			"DimValue":                     {"int", "", "", "", "", ""},
			"ForceFail":                    {"bool", "true", "", "", "", ""},
			"SourceUsesSecondChannel":      {"bool", "false", "", "", "", ""},
		},
	},
	"dim-panel-speaker-cmd": {
		"": {
			"DimSpeakerBy": {"int", "0", "", "", "", ""},
			"ForceFail":    {"bool", "true", "", "", "", ""},
		},
	},
	"edit-conference-cmd": {
		"": {
			"ForceFail": {"bool", "true", "", "", "", ""},
		},
	},
	"edit-ifb-cmd": {
		"": {
			"ForceFail": {"bool", "true", "", "", "", ""},
		},
	},
	"gpio": {
		"GpioInput": {
			"ChannelSelection": {"int", "", "", "", "", ""},
			"DeviceSelection":  {"string", "", "", "", "", ""},
			"GpioType":         {"int", "", "", "", "", "0=Normal|1=Inverted|2=ViaWebUI since version 9.0.1"},
			"LongName":         {"string", "", "", "", "32", ""},
		},
		"GpioOutput": {
			"ChannelSelection": {"int", "", "", "", "", ""},
			"DeviceSelection":  {"string", "", "", "", "", ""},
			"DisplayText":      {"string", "", "", "", "8", ""},
			"GpioType":         {"int", "", "", "", "", "0=Normal|1=Inverted"},
			"LongName":         {"string", "", "", "", "32", ""},
			"OffDelay":         {"int", "", "0", "10000", "", ""},
		},
	},
	"group": {
		"": {
			"IsTrunkEnabled": {"bool", "", "", "", "", ""},
			"KeypadShortcut": {"int", "", "", "", "", ""},
			"Label":          {"string", "", "", "", "8", ""},
			"LongName":       {"string", "", "", "", "32", ""},
			"Name":           {"string", "", "", "", "32", ""},
			"ObjectID":       {"int", "", "", "", "", ""},
			"TrunkingAddr":   {"int", "", "", "", "", ""},
		},
	},
	"ifb": {
		"": {
			"AudioEndpointType": {"string", "", "", "", "", ""},
			"DimLevel":          {"int", "", "", "", "", "0=0 dB|1=-3 dB|2=-6 dB|3=-9 dB|4=-12 dB|5=-18 dB|6=-24 dB|7=mute"},
			"IsTrunkEnabled":    {"bool", "", "", "", "", ""},
			"Label":             {"string", "", "", "", "8", ""},
			"LongName":          {"string", "", "", "", "32", ""},
			"ObjectID":          {"int", "", "", "", "", ""},
			"Owner":             {"int", "", "", "", "", ""},
		},
	},
	"kill-partyline-mic-cmd": {
		"": {
			"ForceFail": {"bool", "true", "", "", "", ""},
		},
	},
	"listen-to-port-cmd": {
		"": {
			"AllowSetInOutGain":       {"bool", "false", "", "", "", ""},
			"DisableCrosspointVolume": {"bool", "false", "", "", "", ""},
			"ForceFail":               {"bool", "true", "", "", "", ""},
			"LocalUsesSecondChannel":  {"bool", "false", "", "", "", ""},
			"Priority":                {"int", "1", "", "", "", ""},
			"SourceUsesSecondChannel": {"bool", "false", "", "", "", ""},
			"TrunkcallPriority":       {"int", "1", "", "", "", ""},
			"TrunkingNetAddr":         {"int", "", "", "", "", ""},
			"TrunkingPortAddr":        {"int", "", "", "", "", ""},
		},
	},
	"logic-cmd": {
		"": {
			"ForceFail":   {"bool", "true", "", "", "", ""},
			"LogicSource": {"int", "", "", "", "", ""},
		},
	},
	"monitor-port-cmd": {
		"": {
			"DestinationUsesSecondChannel": {"bool", "false", "", "", "", ""},
			"ForceFail":                    {"bool", "true", "", "", "", ""},
			"SourceUsesSecondChannel":      {"bool", "false", "", "", "", ""},
			"TrunkingNetAddr":              {"int", "", "", "", "", ""},
			"TrunkingPortAddr":             {"int", "", "", "", "", ""},
		},
	},
	"panel-key": {
		"": {
			"ActionByKeyPressed":        {"int", "1", "", "", "", "0=No Unmute when activated, no mute when|1=Unmute when activated, no mute when deactivated|2=Unmute when activated, mute again when"},
			"AutoLabelFlag":             {"bool", "true", "", "", "", ""},
			"AutoSubtitle":              {"bool", "true", "", "", "", ""},
			"Dim":                       {"bool", "true", "", "", "", ""},
			"ExpansionPanel":            {"int", "", "", "", "", ""},
			"GroupColor":                {"int", "0", "0", "15", "", "16=<none>"},
			"IsInput":                   {"bool", "", "", "", "", ""},
			"KeyMode":                   {"int", "1", "", "", "", "0=Auto|1=Momentary(PTT)|2=Latching"},
			"KeyNumber":                 {"int", "", "", "", "", ""},
			"LabelValue":                {"string", "", "", "", "8", ""},
			"LatchingTimeout":           {"int", "0", "", "", "", "0=Net Default|1=Permanent"},
			"MonitoringState":           {"int", "0", "", "", "", "0=initial off|1=initial on"},
			"Node":                      {"int", "", "", "", "", ""},
			"Page":                      {"int", "", "", "", "", ""},
			"Port":                      {"int", "", "", "", "", ""},
			"RadioButton":               {"int", "0", "", "", "", "0=<none>|1=Group 1|2=Group 2|3=Group 3|4=Group 4"},
			"RestoreVolumeLevel":        {"bool", "false", "", "", "", ""},
			"ScrollEnable":              {"bool", "false", "", "", "", ""},
			"ShowSubtitle":              {"bool", "0", "", "", "", ""},
			"Subtitle":                  {"string", "empty", "", "", "", ""},
			"UseScrollListEntryKeyMode": {"bool", "", "", "", "", ""},
		},
	},
	"port": {
		"": {
			"Alias":              {"string", "", "", "", "8", ""},
			"IsTrunkEnabled":     {"bool", "", "", "", "", ""},
			"IsTrunkLineEnabled": {"bool", "", "", "", "", ""},
			"Label":              {"string", "", "", "", "8", ""},
			"LongName":           {"string", "", "", "", "32", ""},
			"PoolPort":           {"int", "", "", "", "", ""},
			"PoolPortAmount":     {"int", "", "1", "32", "", ""},
			"Subtitle":           {"string", "", "", "", "16", ""},
			"TrunkingPortAddr":   {"int", "", "", "", "", ""},
		},
		"PortAes67": {
			"IpAddress":     {"ip", "", "", "", "", ""},
			"ListenPort":    {"int", "", "", "", "", ""},
			"PacketTime":    {"int", "", "", "", "", "125=0.125 ms|250=0.250 ms|333=0.333 ms|1000=1.000 ms|1333=1.333 ms"},
			"PlayMode":      {"int", "", "", "", "", "0=Synton|1=Synchron"},
			"ReceiveBuffer": {"int", "3", "", "", "", ""},
		},
		"PortAes67Bolero": {
			"BeepDuration":            {"int", "", "", "", "", ""},
			"BeepVol":                 {"int", "", "", "", "", "0=-45 dB|1=-42 dB|14=-3 dB|15=0 dB"},
			"BoleroUserId":            {"int", "", "", "", "", ""},
			"DisplayBrightness":       {"int", "", "", "", "", "0=10%|1=20%|8=90%|9=100%|0=0�|1=90�|2=180�|3=270�"},
			"Enable2nd":               {"bool", "", "", "", "", ""},
			"EnableMuteFunction":      {"bool", "", "", "", "", ""},
			"GroupColorIndication":    {"int", "", "", "", "", "0=Display|1=Key Ring"},
			"HeadSetMode":             {"int", "", "", "", "", "0=Headset lock invalid|1=Headset unlocked|2=Headset locked at speaker"},
			"IndicateBusyOnCallSend":  {"bool", "", "", "", "", ""},
			"IndicateInUseOnCallRecv": {"bool", "", "", "", "", ""},
			"IndicateInUseOnCallSend": {"bool", "", "", "", "", ""},
			"InitialConferenceVol":    {"int", "", "", "", "", "0=6 dB|1=3 dB|6=-12 dB|7=-18 dB|8=-24 dB|9=mute|0=6 dB|1=3 dB|6=-12 dB|7=-18 dB|8=-24 dB|9=mute|0=6 dB|1=3 dB|6=-12 dB|7=-18 dB|8=-24 dB|9=mute"},
			"InitialSingleVol":        {"int", "", "", "", "", "0=6 dB|1=3 dB|6=-12 dB|7=-18 dB|8=-24 dB|9=mute|0=6 dB|1=3 dB|6=-12 dB|7=-18 dB|8=-24 dB|9=mute|0=6 dB|1=3 dB|6=-12 dB|7=-18 dB|8=-24 dB|9=mute"},
			"InputChannel":            {"int", "", "", "", "", ""},
			"LedBrightness":           {"int", "", "", "", "", "0=10%|1=20%|8=90%|9=100%"},
			"MinHeadSetVol":           {"int", "", "", "", "", "0=-45 dB|1=-42 dB|14=-3 dB|15=0 dB"},
			"MinSpeakerVol":           {"int", "", "", "", "", "0=-45 dB|1=-42 dB|14=-3 dB|15=0 dB"},
			"Multicast":               {"ip", "", "", "", "", ""},
			"MulticastPort":           {"int", "", "", "", "", ""},
			"OperationMode":           {"int", "", "", "", "", "0=Talk Mute|1=Talk Listen"},
			"OutputChannel":           {"int", "", "", "", "", ""},
			"ShiftKeyMode":            {"int", "", "", "", "", "0=Shift lock invalid|1=Shift unlocked|2=Locked on norm|3=Locked on shift"},
			"ShowOnReply":             {"bool", "", "", "", "", "0=Talk Mute|1=Talk Listen|0=6 dB|1=3 dB|6=-12 dB|7=-18 dB|8=-24 dB|9=mute"},
			"SpeakerDimLevel":         {"int", "", "", "", "", "0=0 dB|1=-3 dB|2=-6 dB|3=-9 dB|4=-12 dB|5=-18 dB|6=-24 dB|7=mute"},
			"UseGroupColorOnPanel":    {"bool", "", "", "", "", ""},
			"VoxHoldTime":             {"int", "", "", "", "", "-1=no delay|0=50 ms|1=100 ms|2=200 ms|3=400 ms|4=800 ms|5=1600 ms|6=3200 ms|7=6400 ms|0=no delay|1=50 ms|2=100 ms|3=200 ms|4=400 ms|5=800 ms|6=1600 ms|7=3200 ms|8=6400 ms|0=no delay|1=50 ms|2=100 ms|3=200 ms|4=400 ms|5=800 ms|6=1600 ms|7=3200 ms|8=6400 ms"},
			"VoxOffTh":                {"int", "", "", "", "", "0=9 dBu|1=7 dBu|2=5 dBu|30=-51 dBu|31=-53 dBu|0=-39 dBu|1=-41 dBu|2=-43 dBu|6=-51 dBu|7=-53 dBu|0=-39 dBu|1=-41 dBu|2=-43 dBu|6=-51 dBu|7=-53 dBu"},
			"VoxOnTh":                 {"int", "", "", "", "", "0=12 dBu|1=10 dBu|23=-34 dBu|24=-36 dBu|25=permanent|0=12 dBu|1=10 dBu|23=-34 dBu|24=-36 dBu|25=permanent|0=12 dBu|1=10 dBu|23=-34 dBu|24=-36 dBu|25=permanent"},
		},
		"PortAes67Input": {
			"BitDepth":        {"int", "", "", "", "", "16=L16|24=L24"},
			"Channels":        {"int", "", "1", "16", "", ""},
			"Mode":            {"int", "", "0", "1151", "", ""},
			"Multicast":       {"ip", "", "", "", "", ""},
			"Multicast2":      {"ip", "", "", "", "", ""},
			"MulticastPort":   {"int", "", "", "", "", ""},
			"MulticastPort2":  {"int", "", "", "", "", ""},
			"PacketTime":      {"int", "", "", "", "", "125=0.125 ms|250=0.250 ms|333=0.333 ms|1000=1.000 ms|1333=1.333 ms"},
			"PayloadType":     {"int", "", "96", "127", "", ""},
			"PlayMode":        {"int", "", "", "", "", "0=Synton|1=Synchron"},
			"Protocol":        {"int", "", "", "", "", "2=Manual|3=RTSP|5=NMOS"},
			"RTSPUri":         {"string", "", "", "", "", ""},
			"RTSPUri2":        {"string", "", "", "", "", ""},
			"ReceiveBuffer":   {"int", "3", "", "", "", ""},
			"SSRC":            {"string", "", "", "", "", ""},
			"Selection":       {"int", "", "", "", "", ""},
			"SourceIp":        {"ip", "", "", "", "", ""},
			"SourceIp2":       {"ip", "", "", "", "", ""},
			"TimeStampOffset": {"string", "", "", "", "", ""},
		},
		"PortAes67Output": {
			"BitDepth":        {"int", "", "", "", "", "16=L16|24=L24"},
			"Channels":        {"int", "", "1", "16", "", ""},
			"Mode":            {"int", "", "", "", "", ""},
			"Multicase2":      {"ip", "", "", "", "", ""},
			"Multicast":       {"ip", "", "", "", "", ""},
			"MulticastPort":   {"int", "", "", "", "", ""},
			"MulticastPort2":  {"int", "", "", "", "", ""},
			"PacketTime":      {"int", "", "", "", "", "125=0.125 ms|250=0.250 ms|333=0.333 ms|1000=1.000 ms|1333=1.333 ms"},
			"PayloadType":     {"int", "", "96", "127", "", ""},
			"Protocol":        {"int", "", "", "", "", "2=Manual|3=RTSP|5=NMOS"},
			"SSRC":            {"string", "", "", "", "", ""},
			"Selection":       {"int", "", "", "", "", ""},
			"TimeStampOffset": {"string", "", "", "", "", ""},
		},
		"PortSip": {
			"AuthPassword":  {"string", "", "", "", "", ""},
			"AuthUserName":  {"string", "", "", "", "", ""},
			"DisplayName":   {"string", "", "", "", "", ""},
			"DomainServer":  {"string", "", "", "", "", ""},
			"ProxyServer":   {"string", "", "", "", "", ""},
			"Reregister":    {"int", "", "", "", "", ""},
			"SipProtocol":   {"int", "", "", "", "", "0=TCP|1=UDP"},
			"TrustedDomain": {"bool", "", "", "", "", ""},
			"UserName":      {"string", "", "", "", "", ""},
		},
		"PortVoIP": {
			"AudioCodec":           {"int", "", "", "", "", "0=G.711 U-law 8k|8=G.711 A-law 8k|9=G.722 64kbps PLC|84=G.711 U-law 16k|91=G.711 A-law 16k|97=PCM 8k|110=RARe U-law|111=RARe A-law|112=G.722 48kbps PLC"},
			"AudioPacketSize":      {"int", "", "", "", "", "0=20 ms|1=40 ms|2=80 ms|3=160 ms"},
			"DiffServiceCodePoint": {"int", "", "", "", "", ""},
			"LocalSipId":           {"string", "", "", "", "", ""},
			"ReceiveBufferSize":    {"int", "", "", "", "", "0=4 x AudioPacketSize|1=8 x AudioPacketSize|2=16 x AudioPacketSize|3=32 x AudioPacketSize|4=64 x AudioPacketSize|5=128 x AudioPacketSize|6=256 x AudioPacketSize"},
			"RemoteHost":           {"string", "", "", "", "", ""},
			"RemoteSipId":          {"string", "", "", "", "", ""},
			"VoiceActDetection":    {"bool", "", "", "", "", ""},
		},
	},
	"portex": {
		"": {
			"Alias":                  {"string", "", "", "", "8", ""},
			"BeepDuration":           {"int", "", "", "", "", ""},
			"BeepVol":                {"int", "", "", "", "", "0=-45 dB|1=-42 dB|14=-3 dB|15=0 dB"},
			"DisplayBrightness":      {"int", "", "", "", "", "0=10%|1=20%|8=90%|9=100%"},
			"Enable2nd":              {"bool", "", "", "", "", ""},
			"EnableCopyReply":        {"bool", "", "", "", "", ""},
			"EnableMuteFunc":         {"bool", "", "", "", "", ""},
			"FeedbackSuppression":    {"bool", "", "", "", "", ""},
			"FontRotation":           {"int", "", "", "", "", "0=0�"},
			"FontRotationExp":        {"int", "", "", "", "", "0=0�|1=90�|2=180�|3=270�"},
			"GroupColorIndication":   {"int", "", "", "", "", "0=Talk Mute|1=Talk Listen"},
			"HeadSetMode":            {"int", "", "", "", "", "0=Headset lock invalid|1=Headset unlocked|2=Headset locked at speaker"},
			"IncomingCallSignaling":  {"int", "", "", "", "", "0=Blinking|1=Permanent"},
			"IndicateBusyOnCallRecv": {"bool", "", "", "", "", ""},
			"IndicateBusyOnCallSend": {"bool", "", "", "", "", ""},
			"InitialConferenceVol":   {"int", "", "", "", "", "0=6 dB|1=3 dB|6=-12 dB|7=-18 dB|8=-24 dB|9=mute"},
			"InitialIfbVol":          {"int", "", "", "", "", "0=6 dB|1=3 dB|6=-12 dB|7=-18 dB|8=-24 dB|9=mute"},
			"InitialSingleVol":       {"int", "", "", "", "", "0=6 dB|1=3 dB|6=-12 dB|7=-18 dB|8=-24 dB|9=mute"},
			"IsTrunkEnabled":         {"bool", "", "", "", "", ""},
			"IsTrunkLineEnabled":     {"bool", "", "", "", "", ""},
			"KeypadShortcut":         {"int", "", "", "", "", ""},
			"Label":                  {"string", "", "", "", "8", ""},
			"LedBrightness":          {"int", "", "", "", "", "0=10%|1=20%|8=90%|9=100%"},
			"LongName":               {"string", "", "", "", "32", ""},
			"MinHeadSetVol":          {"int", "", "", "", "", "0=-45 dB|1=-42 dB|14=-3 dB|15=0 dB"},
			"MinSpeakerVol":          {"int", "", "", "", "", "0=-45 dB|1=-42 dB|14=-3 dB|15=0 dB"},
			"OperationMode":          {"int", "", "", "", "", "0=Talk Mute|1=Talk Listen"},
			"PoolPortAmount":         {"int", "", "1", "32", "", ""},
			"PortType":               {"int", "", "", "", "", "0=TWO_WIRE_IN|1=TWO_WIRE_OUT|2=FOUR_WIRE|3=FOUR_WIRE_SPLIT|4=RCP_1012E|5=RCP_1028E|6=DCP_1016E|7=RCP_1112|8=RCP_1128|9=DCP_1116|10=CCP_1116|11=RSP_1232HL|12=RSP_1216HL|13=RCP_2016_DP4|14=DCP_2016_DP4|15=RCP_2116_P4|16=DCP_2116_P4|17=RSP_2318_PRO|18=RSP_2318_PLUS|19=RSP_2318_BASIC|20=DSP_2312_PLUS|21=DSP_2312_BASIC|22=RCP_3016_P4|23=DCP_3016_P4|24=DCP_5008|25=DCP_5108|26=DBM_1004E|27=TELEPHONE_CODEC|28=RIF_1032|29=RIF_2064"},
			"ShiftKeyMode":           {"int", "", "", "", "", "0=Shift lock invalid|1=Shift unlocked|2=Locked on norm|3=Locked on shift"},
			"ShowOnReply":            {"bool", "", "", "", "", ""},
			"SpeakerDimLevel":        {"int", "", "", "", "", "0=0 dB|1=-3 dB|2=-6 dB|3=-9 dB|4=-12 dB|5=-18 dB|6=-24 dB|7=mute"},
			"Subtitle":               {"string", "", "", "", "16", ""},
			"TrunkingPortAddr":       {"int", "", "", "", "", ""},
			"UseGroupColorOnPanel":   {"bool", "", "", "", "", ""},
			"VolumeBarIndication":    {"int", "", "", "", "", "0=dynamic|1=permanent"},
			"VoxHoldTime":            {"int", "", "", "", "", "-1=no delay|0=50 ms|1=100 ms|2=200 ms|3=400 ms|4=800 ms|5=1600 ms|6=3200 ms|7=6400 ms"},
			"VoxOffTh":               {"int", "", "", "", "", ""},
			"VoxOnTh":                {"int", "", "", "", "", "0=12 dBu|1=10 dBu|23=-34 dBu|24=-36 dBu|25=permanent"},
		},
		"PortAes67": {
			"IpAddress":     {"ip", "", "", "", "", ""},
			"IpAddress2":    {"ip", "", "", "", "", ""},
			"ListenPort":    {"int", "", "", "", "", ""},
			"ListenPort2":   {"int", "", "", "", "", ""},
			"PacketTime":    {"int", "", "", "", "", "125=0.125 ms|250=0.250 ms|333=0.333 ms|1000=1.000 ms|1333=1.333 ms"},
			"PlayMode":      {"int", "", "", "", "", "0=Synton|1=Synchron"},
			"ReceiveBuffer": {"int", "3", "", "", "", ""},
		},
		"PortAes67Input": {
			"BitDepth":        {"int", "", "", "", "", "16=L16|24=L24"},
			"Channels":        {"int", "", "1", "16", "", ""},
			"Mode":            {"int", "", "0", "1151", "", ""},
			"MulicastPort2":   {"int", "", "", "", "", ""},
			"Multicast":       {"ip", "", "", "", "", ""},
			"Multicast2":      {"ip", "", "", "", "", ""},
			"MulticastPort":   {"int", "", "", "", "", ""},
			"PacketTime":      {"int", "", "", "", "", "125=0.125 ms|250=0.250 ms|333=0.333 ms|1000=1.000 ms|1333=1.333 ms"},
			"PayloadType":     {"int", "", "96", "127", "", ""},
			"PlayMode":        {"int", "", "", "", "", "0=Synton|1=Synchron"},
			"Protocol":        {"int", "", "", "", "", "2=Manual|3=RTSP|5=NMOS"},
			"RTSPUri":         {"string", "", "", "", "", ""},
			"RTSPUri2":        {"string", "", "", "", "", ""},
			"ReceiveBuffer":   {"int", "3", "", "", "", ""},
			"SSRC":            {"string", "", "", "", "", ""},
			"Selection":       {"int", "", "", "", "", ""},
			"SourceIp":        {"ip", "", "", "", "", ""},
			"SourceIp2":       {"ip", "", "", "", "", ""},
			"TimeStampOffset": {"string", "", "", "", "", ""},
		},
		"PortAes67Output": {
			"BitDepth":        {"int", "", "", "", "", "16=L16|24=L24"},
			"Channels":        {"int", "", "1", "16", "", ""},
			"Mode":            {"int", "", "0", "1151", "", ""},
			"MulicastPort2":   {"int", "", "", "", "", ""},
			"Multicast":       {"ip", "", "", "", "", ""},
			"Multicast2":      {"ip", "", "", "", "", ""},
			"MulticastPort":   {"int", "", "", "", "", ""},
			"PacketTime":      {"int", "", "", "", "", "125=0.125 ms|250=0.250 ms|333=0.333 ms|1000=1.000 ms|1333=1.333 ms"},
			"PayloadType":     {"int", "", "96", "127", "", ""},
			"Protocol":        {"int", "", "", "", "", "2=Manual|3=RTSP|5=NMOS"},
			"RTSPUri":         {"string", "", "", "", "", ""},
			"RTSPUri2":        {"string", "", "", "", "", ""},
			"SSRC":            {"string", "", "", "", "", ""},
			"Selection":       {"int", "", "", "", "", ""},
			"SourceIp":        {"ip", "", "", "", "", ""},
			"SourceIp2":       {"ip", "", "", "", "", ""},
			"TimeStampOffset": {"string", "", "", "", "", ""},
		},
		"PortAes67Trunkline": {
			"LocalSipId":    {"string", "", "", "", "", ""},
			"PacketTime":    {"int", "", "", "", "", ""},
			"PlayMode":      {"int", "", "", "", "", "0=synton|1=synchron"},
			"ReceiveBuffer": {"int", "", "", "", "", ""},
			"RemoteHost":    {"string", "", "", "", "", ""},
			"RemoteSipId":   {"string", "", "", "", "", ""},
			"RemoteSipPort": {"int", "", "", "", "", ""},
			"SipCalleeMode": {"bool", "", "", "", "", ""},
		},
		"PortBolero": {
			"BoleroUserId":          {"int", "", "", "", "", ""},
			"Multicast":             {"ip", "", "", "", "", ""},
			"MulticastPort":         {"int", "", "", "", "", ""},
			"MulticastPortToBolero": {"int", "", "", "", "", ""},
			"OperationMode":         {"int", "", "", "", "", ""},
		},
		"PortCodec": {
			"AutoAnswer":        {"bool", "", "", "", "", ""},
			"AutoDialNumber":    {"string", "", "", "", "", ""},
			"ChannelSelection":  {"int", "", "", "", "", ""},
			"DeviceSelection":   {"string", "", "", "", "", ""},
			"InputChannel":      {"int", "", "", "", "", ""},
			"IsAutoDialEnabled": {"bool", "", "", "", "", ""},
			"OutputChannel":     {"int", "", "", "", "", ""},
		},
		"PortMadi": {
			"InputChannel":  {"int", "", "", "", "", ""},
			"OutputChannel": {"int", "", "", "", "", ""},
		},
		"PortSip": {
			"AuthPassword":     {"string", "", "", "", "", ""},
			"AuthUserName":     {"string", "", "", "", "", ""},
			"DisplayName":      {"string", "", "", "", "", ""},
			"DomainServer":     {"string", "", "", "", "", ""},
			"EnableAutoHangUp": {"bool", "", "", "", "", ""},
			"ProxyServer":      {"string", "", "", "", "", ""},
			"Reregister":       {"int", "", "", "", "", ""},
			"SipProtocol":      {"int", "", "", "", "", "0=TCP|1=UDP"},
			"TrustedDomain":    {"bool", "", "", "", "", ""},
			"UserName":         {"string", "", "", "", "", ""},
		},
		"PortVoIP": {
			"AudioCodec":           {"int", "", "", "", "", "0=G.711 U-law 8k|8=G.711 A-law 8k|9=G.722 64kbps PLC|84=G.711 U-law 16k|91=G.711 A-law 16k"},
			"AudioPacketSize":      {"int", "", "", "", "", "0=20 ms|1=40 ms|2=80 ms|3=160 ms"},
			"DiffServiceCodePoint": {"int", "", "", "", "", ""},
			"LocalSipId":           {"string", "", "", "", "", ""},
			"ReceiveBufferSize":    {"int", "", "", "", "", "0=4 x AudioPacketSize|1=8 x AudioPacketSize|2=16 x AudioPacketSize|3=32 x AudioPacketSize|4=64 x AudioPacketSize|5=128 x AudioPacketSize|6=256 x AudioPacketSize"},
			"RemoteHost":           {"string", "", "", "", "", ""},
			"RemoteSipId":          {"string", "", "", "", "", ""},
			"VoiceActDetection":    {"bool", "", "", "", "", ""},
		},
	},
	"remote-key-cmd": {
		"": {
			"ExpansionPanel":    {"int", "", "", "", "", ""},
			"ForceFail":         {"bool", "true", "", "", "", ""},
			"KeyNumber":         {"int", "", "", "", "", ""},
			"KeyPage":           {"int", "", "", "", "", "1=shift page|2=virtual key|1=shift page|2=virtual key"},
			"LockKey":           {"bool", "false", "", "", "", ""},
			"MarkerFlag":        {"bool", "false", "", "", "", ""},
			"MarkerValue":       {"int", "0", "", "", "", ""},
			"PressKey":          {"bool", "false", "", "", "", ""},
			"PressKeySecondary": {"bool", "false", "", "", "", ""},
			"TextFlag":          {"bool", "false", "", "", "", ""},
			"TextValue":         {"string", "", "", "", "", ""},
		},
	},
	"reply-cmd": {
		"": {
			"DuplexEnabledForCall2Port": {"bool", "false", "", "", "", ""},
			"EnableForCallsFromConf":    {"bool", "false", "", "", "", ""},
			"ForceFail":                 {"bool", "true", "", "", "", ""},
			"Priority":                  {"int", "1", "", "", "", "0=Below Standard|1=Standard|2=High|3=Paging|4=Emergency"},
			"ScrollEnabled":             {"bool", "false", "", "", "", ""},
		},
	},
	"route-cmd": {
		"": {
			"DestinationUsesSecondChannel": {"bool", "false", "", "", "", ""},
			"DisableCrosspointVolume":      {"bool", "false", "", "", "", ""},
			"ForceFail":                    {"bool", "true", "", "", "", ""},
			"Priority":                     {"int", "1", "", "", "", ""},
			"SourceUsesSecondChannel":      {"bool", "false", "", "", "", ""},
		},
	},
	"select-audiopatch-cmd": {
		"": {
			"Audiopatch": {"int", "", "", "", "", ""},
			"ForceFail":  {"bool", "true", "", "", "", ""},
		},
	},
	"send-string-cmd": {
		"": {
			"ForceFail":  {"bool", "true", "", "", "", ""},
			"SendString": {"string", "", "", "", "", ""},
		},
	},
	"set-input-output-gain-cmd": {
		"": {
			"ForceFail": {"bool", "true", "", "", "", ""},
			"IsInput":   {"bool", "", "", "", "", ""},
		},
	},
	"sidetone-cmd": {
		"": {
			"EnableForHeadsetMode": {"bool", "false", "", "", "", ""},
			"EnableForSpeakerMode": {"bool", "false", "", "", "", ""},
			"ForceFail":            {"bool", "true", "", "", "", ""},
			"NormSidetoneLevel":    {"int", "-6", "", "", "", ""},
		},
	},
	"switch-gpio-out-cmd": {
		"": {
			"ForceFail":  {"bool", "true", "", "", "", ""},
			"GPIONumber": {"int", "", "", "", "", ""},
			"Slot":       {"int", "", "", "", "", ""},
		},
	},
	"telephone-dial-hangup-cmd": {
		"": {
			"ForceFail": {"bool", "true", "", "", "", ""},
			"Function":  {"int", "", "", "", "", ""},
		},
	},
	"telephone-dial-keypad-cmd": {
		"": {
			"ForceFail":   {"bool", "true", "", "", "", ""},
			"KeyFunction": {"int", "", "", "", "", ""},
		},
	},
	"virtual-key": {
		"NewProperties": {
			"AutoLabelFlag":           {"bool", "", "", "", "", ""},
			"DimSpeakerWhenActivated": {"bool", "", "", "", "", ""},
			"KeyMode":                 {"int", "", "", "", "", ""},
			"LatchingTimeOut":         {"int", "", "", "", "", ""},
			"RadioButton":             {"int", "", "", "", "", "0=None|1=Group 1|2=Group 2|3=Group 3|4=Group 4"},
			"RestartLatchingTimer":    {"bool", "", "", "", "", ""},
		},
	},
}
