package provider

import (
	"time"

	"dhs/internal/snmp/mib"
	"dhs/internal/snmp/mibgen"
)

// DHSModule describes DHS-MIB, BY-SYSTEMS' own module under IANA Private
// Enterprise Number 54981, from the tree an agent serves.
//
// The fixed part — the arcs, the agent's identity, the notifications — is
// written here once. The objects come from the tree, so a MIB generated
// from a running agent's tree cannot describe objects it does not serve,
// or miss ones it does.
//
// A new object or notification is a new REVISION: add it at the top of
// dhsRevisions, dated, saying what changed. Managers compare LAST-UPDATED
// to decide whether the module they hold is stale.
func DHSModule(tree *MIB, contact string) (mibgen.Module, error) {
	objects, err := tree.Definitions(mib.DHS)
	if err != nil {
		return mibgen.Module{}, err
	}
	if contact == "" {
		contact = DHSOrganization
	}
	return mibgen.Module{
		Name:         "DHS-MIB",
		Identity:     "dhsMIB",
		OID:          mib.DHSMIB,
		Organization: DHSOrganization,
		ContactInfo:  contact,
		Description: "The identity, objects and notifications of dhs, the BY-SYSTEMS\n" +
			"broadcast control gateway, under IANA Private Enterprise Number 54981.\n" +
			"Generated by `dhs producer snmp mib` from the tree the agent serves.",
		Revisions: dhsRevisions,
		Branches: []mibgen.Branch{
			{Name: "bySystems", OID: mib.DHS},
			{Name: "dhsProducts", OID: mib.DHSProducts,
				Description: "The products BY-SYSTEMS registers; each is a sysObjectID value."},
			{Name: "dhsAgent", OID: mib.DHSAgent,
				Description: "The dhs SNMP agent. It is the sysObjectID.0 the agent reports and\n" +
					"the enterprise its SNMPv1 traps carry."},
			{Name: "dhsAgentNotifications", OID: mib.DHSAgent.Append(0)},
			{Name: "dhsObjects", OID: mib.DHSObjects},
		},
		Objects: objects,
		Notifications: []mibgen.Notification{{
			Name: "dhsTestNotification", OID: mib.DHSTestNotification,
			Description: "Sent on demand by `dhs producer snmp trap` to prove a receiver is\n" +
				"reachable before anything depends on it. It reports no event and\n" +
				"carries no objects. In SNMPv1 it is enterprise dhsAgent, generic 6,\n" +
				"specific 1.",
		}},
	}, nil
}

// DHSOrganization is the registrant of PEN 54981 as IANA lists it.
const DHSOrganization = "BY-SYSTEMS SPRL"

// dhsRevisions is DHS-MIB's history, newest first.
var dhsRevisions = []mibgen.Revision{
	{Date: time.Date(2026, 9, 11, 0, 0, 0, 0, time.UTC),
		Description: "Initial version: the agent's identity and the test notification."},
}
