module.exports = {
    inputFiles: ['./src/'],
    mode: 'file',
    // mode: 'modules',
    includeDeclarations: true,
    tsconfig: 'tsconfig.json',
    out: './docs/dist/docs-web/',
    excludePrivate: false,
    excludeProtected: false,
    excludeExternals: true,
    readme: './README.md',
    name: 'Probel SW-P-8 protocol Library project',
    includeVersion: true,
    ignoreCompilerErrors: true,
    plugin: 'none',
    listInvalidSymbolLinks: false,
    entryPoint: './README.md',
    categorizeByGroup: true,
    media: './medias',
    version: '',
    gitRemote: 'upstream',
    gitRevision: 'branch',
    theme: 'default'
};
