package export

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"acp/internal/protocol"
)

// WriteYAML emits a Snapshot as YAML. We deliberately avoid importing
// gopkg.in/yaml.v3 — the project rule is "stdlib only, single-binary
// copy-paste deploy". This hand-rolled emitter handles exactly the
// shape a Snapshot needs: top-level map, nested maps, lists of scalars
// and maps, and scalar leaves (string, int, float, bool).
//
// Not a general-purpose YAML writer. Not a parser (use ReadJSON and
// drop YAML input for now — import is JSON-only). Not a beauty
// contest: prioritises correctness and 2-space indentation.
func WriteYAML(w io.Writer, s *Snapshot) error {
	var sb strings.Builder

	sb.WriteString("# acp snapshot — generated by cmd/acp\n")
	sb.WriteString("device:\n")
	writeKV(&sb, 2, "ip", s.Device.IP)
	writeKV(&sb, 2, "port", s.Device.Port)
	writeKV(&sb, 2, "protocol", s.Device.Protocol)
	if s.Device.ProtocolVersion > 0 {
		writeKV(&sb, 2, "protocol_version", s.Device.ProtocolVersion)
	}
	writeKV(&sb, 2, "num_slots", s.Device.NumSlots)

	if s.Generator != "" {
		writeKV(&sb, 0, "generator", s.Generator)
	}
	writeKV(&sb, 0, "created_at", s.CreatedAt.UTC().Format("2006-01-02T15:04:05Z"))

	sb.WriteString("slots:\n")
	for _, slot := range s.Slots {
		sb.WriteString("  - slot: ")
		sb.WriteString(fmt.Sprintf("%d\n", slot.Slot))
		if slot.Status != "" {
			writeKV(&sb, 4, "status", slot.Status)
		}
		writeKV(&sb, 4, "walked_at", slot.WalkedAt.UTC().Format("2006-01-02T15:04:05Z"))

		// Check if any object has path depth > 2 (ACP2 hierarchical).
		hierarchical := false
		for _, o := range slot.Objects {
			if len(o.Path) > 2 {
				hierarchical = true
				break
			}
		}

		if hierarchical {
			// ACP2: build nested tree from Path and render hierarchically.
			root := buildObjectTree(slot.Objects)
			writeTreeNode(&sb, 4, root)
		} else {
			// ACP1: flat group → list of objects.
			groups := groupByPath(slot.Objects)
			for _, gname := range groups.order {
				sb.WriteString("    ")
				sb.WriteString(gname)
				sb.WriteString(":\n")
				for _, o := range groups.items[gname] {
					writeObject(&sb, 6, o)
				}
			}
		}
	}

	if _, err := io.WriteString(w, sb.String()); err != nil {
		return fmt.Errorf("yaml write: %w", err)
	}
	return nil
}

// objectTreeNode is a node in the hierarchical object tree built from
// flat Path slices. Nodes with obj != nil are leaf/value objects;
// nodes with only children are containers (rendered as YAML maps).
type objectTreeNode struct {
	name     string
	obj      *protocol.Object // nil for pure container nodes
	children []*objectTreeNode
	childIdx map[string]int // name → index into children
}

// buildObjectTree constructs a tree from flat objects using their Path.
// Path[0] is always ROOT_NODE_V2 for ACP2 — we skip it and start from
// Path[1] (BOARD, PSU, etc.) so the tree matches Cerebrum's view.
func buildObjectTree(objs []protocol.Object) *objectTreeNode {
	root := &objectTreeNode{name: "root", childIdx: map[string]int{}}
	for i := range objs {
		o := &objs[i]
		// Skip the root node object itself (path = ["ROOT_NODE_V2"]).
		if len(o.Path) <= 1 {
			continue
		}
		// Walk from path[1] onward, creating container nodes as needed.
		cur := root
		for _, seg := range o.Path[1:] {
			idx, exists := cur.childIdx[seg]
			if !exists {
				idx = len(cur.children)
				cur.childIdx[seg] = idx
				cur.children = append(cur.children, &objectTreeNode{
					name:     seg,
					childIdx: map[string]int{},
				})
			}
			cur = cur.children[idx]
		}
		// If this is a leaf (has a value kind), attach the object.
		// Node/container objects (kind=raw) just create the tree structure.
		if o.Kind != protocol.KindRaw {
			cur.obj = o
		}
	}
	return root
}

// writeTreeNode renders a tree node and its children as nested YAML.
func writeTreeNode(sb *strings.Builder, indent int, node *objectTreeNode) {
	pad := strings.Repeat(" ", indent)
	for _, child := range node.children {
		// Write the node name as a YAML map key.
		sb.WriteString(pad)
		sb.WriteString(yamlString(child.name))
		sb.WriteString(":\n")

		// Write this node's own properties (if it's a leaf with a value).
		if child.obj != nil {
			writeTreeLeaf(sb, indent+2, child.obj)
		}

		// Recurse into children.
		writeTreeNode(sb, indent+2, child)
	}
}

// writeTreeLeaf renders properties of a leaf object under its parent key.
func writeTreeLeaf(sb *strings.Builder, indent int, o *protocol.Object) {
	pad := strings.Repeat(" ", indent)

	writeKVPad(sb, pad, "id", o.ID)
	writeKVPad(sb, pad, "kind", kindName(o.Kind))
	writeKVPad(sb, pad, "access", accessStr(o.Access))
	if o.Unit != "" {
		writeKVPad(sb, pad, "unit", o.Unit)
	}

	switch o.Kind {
	case protocol.KindInt, protocol.KindUint, protocol.KindFloat:
		writeKVPad(sb, pad, "min", o.Min)
		writeKVPad(sb, pad, "max", o.Max)
		writeKVPad(sb, pad, "step", o.Step)
		writeKVPad(sb, pad, "default", o.Def)
	case protocol.KindEnum:
		writeKVPad(sb, pad, "enum_items", o.EnumItems)
		writeKVPad(sb, pad, "default", o.Def)
	case protocol.KindString:
		if o.MaxLen > 0 {
			writeKVPad(sb, pad, "max_len", o.MaxLen)
		}
	}

	writeValue(sb, pad, *o)
}

// orderedGroups holds objects bucketed by path name, with insertion
// order preserved for stable output.
type orderedGroups struct {
	order []string
	items map[string][]protocol.Object
}

// groupByPath partitions objects by their group name. For ACP1 this is
// the Group field (identity/control/status/alarm). For ACP2 the Group
// field is empty — we use the second Path element (BOARD, PSU, etc.)
// since Path[0] is always ROOT_NODE_V2.
func groupByPath(objs []protocol.Object) orderedGroups {
	g := orderedGroups{items: map[string][]protocol.Object{}}
	for _, o := range objs {
		name := o.Group
		if name == "" && len(o.Path) > 1 {
			name = o.Path[1] // ACP2: skip ROOT_NODE_V2, use BOARD/PSU/etc.
		} else if name == "" && len(o.Path) > 0 {
			name = o.Path[0]
		}
		if name == "" {
			name = "other"
		}
		if _, exists := g.items[name]; !exists {
			g.order = append(g.order, name)
		}
		g.items[name] = append(g.items[name], o)
	}
	return g
}

// writeObject renders one protocol.Object as a YAML list item.
// Each list item starts with "- " at indent-2 and continues with
// key:value pairs at indent (the `- ` and subsequent keys are aligned
// so the overall indentation is indent+2 for child fields).
func writeObject(sb *strings.Builder, indent int, o protocol.Object) {
	pad := strings.Repeat(" ", indent)
	sb.WriteString(pad)
	sb.WriteString("- label: ")
	sb.WriteString(yamlString(o.Label))
	sb.WriteByte('\n')

	childPad := strings.Repeat(" ", indent+2)

	writeKVPad(sb, childPad, "id", o.ID)
	writeKVPad(sb, childPad, "kind", kindName(o.Kind))
	writeKVPad(sb, childPad, "access", accessStr(o.Access))
	if o.SubGroupMarker {
		writeKVPad(sb, childPad, "sub_group_marker", true)
	}
	if o.Unit != "" {
		writeKVPad(sb, childPad, "unit", o.Unit)
	}

	switch o.Kind {
	case protocol.KindInt, protocol.KindUint, protocol.KindFloat:
		writeKVPad(sb, childPad, "min", o.Min)
		writeKVPad(sb, childPad, "max", o.Max)
		writeKVPad(sb, childPad, "step", o.Step)
		writeKVPad(sb, childPad, "default", o.Def)
	case protocol.KindEnum:
		writeKVPad(sb, childPad, "enum_items", o.EnumItems)
		writeKVPad(sb, childPad, "default", o.Def)
	case protocol.KindString:
		if o.MaxLen > 0 {
			writeKVPad(sb, childPad, "max_len", o.MaxLen)
		}
	case protocol.KindAlarm:
		writeKVPad(sb, childPad, "alarm_priority", o.AlarmPriority)
		writeKVPad(sb, childPad, "alarm_tag", fmt.Sprintf("0x%02X", o.AlarmTag))
		if o.AlarmOnMsg != "" {
			writeKVPad(sb, childPad, "alarm_on", o.AlarmOnMsg)
		}
		if o.AlarmOffMsg != "" {
			writeKVPad(sb, childPad, "alarm_off", o.AlarmOffMsg)
		}
	}

	writeValue(sb, childPad, o)
}

// writeValue renders the current value of an Object — the one field
// the import pipeline actually writes back. Kept in one place so the
// encoding is consistent across all kinds.
func writeValue(sb *strings.Builder, pad string, o protocol.Object) {
	v := o.Value
	switch v.Kind {
	case protocol.KindInt:
		writeKVPad(sb, pad, "value", v.Int)
	case protocol.KindUint:
		writeKVPad(sb, pad, "value", v.Uint)
	case protocol.KindFloat:
		writeKVPad(sb, pad, "value", v.Float)
	case protocol.KindEnum:
		writeKVPad(sb, pad, "value", v.Enum)
		if v.Str != "" {
			writeKVPad(sb, pad, "value_name", v.Str)
		}
	case protocol.KindString:
		writeKVPad(sb, pad, "value", v.Str)
	case protocol.KindIPAddr:
		writeKVPad(sb, pad, "value",
			fmt.Sprintf("%d.%d.%d.%d",
				v.IPAddr[0], v.IPAddr[1], v.IPAddr[2], v.IPAddr[3]))
	case protocol.KindFrame:
		if len(v.SlotStatus) > 0 {
			sb.WriteString(pad)
			sb.WriteString("slot_status:\n")
			inner := pad + "  "
			for i, st := range v.SlotStatus {
				sb.WriteString(inner)
				sb.WriteString("- {slot: ")
				sb.WriteString(fmt.Sprintf("%d", i))
				sb.WriteString(", status: ")
				sb.WriteString(yamlString(st.String()))
				sb.WriteString("}\n")
			}
		}
	}
}

// writeKV writes "key: value\n" at the given indent. Generic over the
// common Go types we need; unknown types fall back to %v.
func writeKV(sb *strings.Builder, indent int, key string, val any) {
	pad := strings.Repeat(" ", indent)
	writeKVPad(sb, pad, key, val)
}

// writeKVPad is writeKV with a pre-built indent string, useful in
// inner loops where we don't want to re-strings.Repeat on every call.
func writeKVPad(sb *strings.Builder, pad string, key string, val any) {
	sb.WriteString(pad)
	sb.WriteString(key)
	sb.WriteString(": ")
	sb.WriteString(yamlScalar(val))
	sb.WriteByte('\n')
}

// yamlScalar formats one scalar value. Lists are flow-style `[a, b]`
// to keep the output compact. Anything we don't recognise is round-
// tripped through JSON — cheap insurance against formatting bugs.
func yamlScalar(v any) string {
	switch t := v.(type) {
	case nil:
		return "null"
	case string:
		return yamlString(t)
	case bool:
		if t {
			return "true"
		}
		return "false"
	case int:
		return fmt.Sprintf("%d", t)
	case int64:
		return fmt.Sprintf("%d", t)
	case uint8:
		return fmt.Sprintf("%d", t)
	case uint64:
		return fmt.Sprintf("%d", t)
	case float64:
		return fmt.Sprintf("%g", t)
	case []string:
		var b strings.Builder
		b.WriteByte('[')
		for i, s := range t {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(yamlString(s))
		}
		b.WriteByte(']')
		return b.String()
	}
	// Fallback: json-encode, strip outer whitespace. Valid JSON is
	// valid YAML, so this always produces a parseable scalar.
	raw, err := json.Marshal(v)
	if err != nil {
		return "null"
	}
	return string(raw)
}

// yamlString quotes a string only when necessary — identifiers and
// simple words go bare for readability; anything with special chars,
// leading/trailing space, or control characters gets double-quoted
// with JSON-style escaping.
func yamlString(s string) string {
	if s == "" {
		return `""`
	}
	needQuote := false
	for _, r := range s {
		if r < 0x20 || r == '"' || r == '\\' || r == ':' || r == '#' ||
			r == '[' || r == ']' || r == '{' || r == '}' || r == ',' || r == '&' ||
			r == '*' || r == '!' || r == '|' || r == '>' || r == '\'' ||
			r == '%' || r == '@' || r == '`' {
			needQuote = true
			break
		}
	}
	if !needQuote && (s[0] == ' ' || s[len(s)-1] == ' ') {
		needQuote = true
	}
	// Numbers, "true", "false", "null", "yes", "no" must be quoted to
	// avoid type ambiguity.
	switch strings.ToLower(s) {
	case "true", "false", "null", "yes", "no", "on", "off":
		needQuote = true
	}
	if !needQuote {
		return s
	}
	// JSON string encoding produces a valid double-quoted YAML scalar.
	raw, _ := json.Marshal(s)
	return string(raw)
}
