package export

import (
	"bufio"
	"bytes"
	"errors"
	"strings"
	"testing"
	"time"

	"dhs/internal/consumer"
)

// TestWriteYAML_ACP1 — the exact document an ACP1 snapshot produces:
// device header, optional generator/protocol_version, then group →
// label → properties. Groups come from Group, then Path[0], then
// "other"; unlabeled objects are keyed obj_<id>; a duplicate label in
// one group keeps the last object; scalars needing quotes get them.
func TestWriteYAML_ACP1(t *testing.T) {
	snap := &Snapshot{
		Device:    DeviceInfo{IP: "10.6.239.113", Port: 2071, Protocol: "acp1", ProtocolVersion: 2, NumSlots: 1},
		Generator: "acp 1.0",
		CreatedAt: time.Date(2026, 4, 16, 12, 0, 0, 0, time.UTC),
		Slots: []SlotDump{{Slot: 1, Status: "present", WalkedAt: time.Date(2026, 4, 16, 12, 0, 0, 0, time.UTC),
			Objects: []consumer.Object{
				{Group: "control", Path: []string{"control"}, ID: 7, Label: "GainA", Kind: consumer.KindFloat, Access: 3, Unit: "%",
					Min: float64(0), Max: float64(150), Step: float64(1), Def: float64(100),
					Value: consumer.Value{Kind: consumer.KindFloat, Float: 50.8}},
				{Path: []string{"sensors"}, ID: 1, Label: "Temp", Kind: consumer.KindInt, Access: 1, Min: int64(-10), Max: int64(90),
					Value: consumer.Value{Kind: consumer.KindInt, Int: 42}},
				{Label: "Uptime", ID: 2, Kind: consumer.KindUint, Access: 1, Value: consumer.Value{Kind: consumer.KindUint, Uint: 99}},
				{Group: "identity", ID: 5, Kind: consumer.KindString, Access: 1, MaxLen: 8, Value: consumer.Value{Kind: consumer.KindString, Str: "RRS18"}},
				{Group: "control", Label: "Mode", ID: 8, Kind: consumer.KindEnum, Access: 3, EnumItems: []string{"Off", "On"}, Def: uint64(1),
					Value: consumer.Value{Kind: consumer.KindEnum, Enum: 1, Str: "On"}},
				{Group: "control", Label: "Mode", ID: 9, Kind: consumer.KindEnum, Access: 3, EnumItems: []string{"Off", "On"}, Def: uint64(1),
					Value: consumer.Value{Kind: consumer.KindEnum, Enum: 0}},
				{Group: "network", Label: "IP", ID: 3, Kind: consumer.KindIPAddr, Access: 1,
					Value: consumer.Value{Kind: consumer.KindIPAddr, IPAddr: [4]byte{10, 6, 250, 101}}},
				{Group: "frame", Label: "Slots", ID: 4, Kind: consumer.KindFrame, Access: 1,
					Value: consumer.Value{Kind: consumer.KindFrame, SlotStatus: []consumer.SlotStatus{consumer.SlotPresent, consumer.SlotNoCard}}},
				{Group: "frame", Label: "Empty frame", ID: 6, Kind: consumer.KindFrame, Access: 1, Value: consumer.Value{Kind: consumer.KindFrame}},
				{Group: "alarm", Label: "true", ID: 11, Kind: consumer.KindBool, Value: consumer.Value{Kind: consumer.KindBool, Bool: true}},
			}}},
	}
	want := `# acp snapshot — generated by cmd/acp
device:
  ip: 10.6.239.113
  port: 2071
  protocol: acp1
  protocol_version: 2
  num_slots: 1
generator: acp 1.0
created_at: "2026-04-16T12:00:00Z"
slots:
  - slot: 1
    status: present
    walked_at: "2026-04-16T12:00:00Z"
    control:
      GainA:
        id: 7
        kind: float
        access: RW-
        unit: "%"
        min: 0
        max: 150
        step: 1
        default: 100
        value: 50.8
      Mode:
        id: 9
        kind: enum
        access: RW-
        enum_items: ["Off", "On"]
        default: 1
        value: 0
    sensors:
      Temp:
        id: 1
        kind: int
        access: R--
        min: -10
        max: 90
        step: null
        default: null
        value: 42
    other:
      Uptime:
        id: 2
        kind: uint
        access: R--
        min: null
        max: null
        step: null
        default: null
        value: 99
    identity:
      obj_5:
        id: 5
        kind: string
        access: R--
        max_len: 8
        value: RRS18
    network:
      IP:
        id: 3
        kind: ipaddr
        access: R--
        value: 10.6.250.101
    frame:
      Slots:
        id: 4
        kind: frame
        access: R--
        slot_status:
          - {slot: 0, status: present}
          - {slot: 1, status: no_card}
      Empty frame:
        id: 6
        kind: frame
        access: R--
    alarm:
      "true":
        id: 11
        kind: bool
        access: ---
`
	var buf bytes.Buffer
	if err := WriteYAML(&buf, snap); err != nil {
		t.Fatalf("WriteYAML: %v", err)
	}
	if buf.String() != want {
		t.Errorf("YAML mismatch\n--- got ---\n%s\n--- want ---\n%s", buf.String(), want)
	}
}

// TestWriteYAML_ACP2 — an ACP2 snapshot drops the ROOT_NODE_V2 root
// object, nests every path segment, and renders containers (kind=raw)
// as bare maps around their leaves.
func TestWriteYAML_ACP2(t *testing.T) {
	snap := &Snapshot{
		Device:    DeviceInfo{IP: "10.41.40.195", Port: 2072, Protocol: "acp2", NumSlots: 1},
		CreatedAt: time.Date(2026, 4, 19, 12, 0, 0, 0, time.UTC),
		Slots: []SlotDump{{Slot: 0, WalkedAt: time.Date(2026, 4, 19, 12, 0, 0, 0, time.UTC),
			Objects: []consumer.Object{
				{Path: []string{"ROOT_NODE_V2"}, ID: 1, Label: "ROOT_NODE_V2", Kind: consumer.KindRaw},
				{Path: []string{"ROOT_NODE_V2", "BOARD"}, ID: 2, Label: "BOARD", Kind: consumer.KindRaw},
				{Path: []string{"ROOT_NODE_V2", "BOARD", "ACP Trace"}, ID: 47431, Label: "ACP Trace", Kind: consumer.KindEnum, Access: 3,
					EnumItems: []string{"Off", "On"}, Value: consumer.Value{Kind: consumer.KindEnum, Enum: 0, Str: "Off"}},
				{Path: []string{"ROOT_NODE_V2", "STATUS", "PSU", "1", "Present"}, ID: 60001, Label: "Present", Kind: consumer.KindString, Access: 1,
					Value: consumer.Value{Kind: consumer.KindString, Str: "yes: maybe"}},
			}}},
	}
	want := `# acp snapshot — generated by cmd/acp
device:
  ip: 10.41.40.195
  port: 2072
  protocol: acp2
  num_slots: 1
created_at: "2026-04-19T12:00:00Z"
slots:
  - slot: 0
    walked_at: "2026-04-19T12:00:00Z"
    BOARD:
      ACP Trace:
        id: 47431
        kind: enum
        access: RW-
        enum_items: ["Off", "On"]
        default: null
        value: 0
        value_name: "Off"
    STATUS:
      PSU:
        1:
          Present:
            id: 60001
            kind: string
            access: R--
            value: "yes: maybe"
`
	var buf bytes.Buffer
	if err := WriteYAML(&buf, snap); err != nil {
		t.Fatalf("WriteYAML: %v", err)
	}
	if buf.String() != want {
		t.Errorf("YAML mismatch\n--- got ---\n%s\n--- want ---\n%s", buf.String(), want)
	}
	// And the reader takes it back: the tree is the contract both ways.
	back, err := ReadYAML(strings.NewReader(buf.String()))
	if err != nil {
		t.Fatalf("ReadYAML: %v", err)
	}
	var leaves []string
	for _, o := range back.Slots[0].Objects {
		if o.ID != 0 {
			leaves = append(leaves, strings.Join(o.Path, "."))
		}
	}
	if got := strings.Join(leaves, ","); got != "BOARD.ACP Trace,STATUS.PSU.1.Present" {
		t.Errorf("read-back leaf paths: %s", got)
	}
}

// TestWriteYAML_SinkError — a dead sink is reported with the yaml
// prefix.
func TestWriteYAML_SinkError(t *testing.T) {
	err := WriteYAML(brokenSink{}, &Snapshot{})
	if !errors.Is(err, errSink) || !strings.HasPrefix(err.Error(), "yaml write:") {
		t.Errorf("got %v, want yaml write: sink closed", err)
	}
}

// TestYAMLScalar — every Go type a snapshot field can hold, and the
// JSON fallback for anything else (valid JSON is valid YAML).
func TestYAMLScalar(t *testing.T) {
	cases := []struct {
		name string
		in   any
		want string
	}{
		{"nil", nil, "null"},
		{"bare string", "GainA", "GainA"},
		{"true", true, "true"},
		{"false", false, "false"},
		{"int", int(-3), "-3"},
		{"int64", int64(1 << 40), "1099511627776"},
		{"uint8", uint8(7), "7"},
		{"uint64", uint64(1 << 63), "9223372036854775808"},
		{"float64", float64(0.5), "0.5"},
		{"string list quotes the boolean words", []string{"Off", "On", "a:b", "x"}, `["Off", "On", "a:b", x]`},
		{"empty list", []string{}, "[]"},
		{"map falls back to JSON", map[string]int{"k": 1}, `{"k":1}`},
		{"unencodable is null", make(chan int), "null"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := yamlScalar(c.in); got != c.want {
				t.Errorf("yamlScalar(%#v) = %q, want %q", c.in, got, c.want)
			}
		})
	}
}

// TestYAMLString — quoting only where a YAML parser would otherwise
// change the value: specials, edge spaces, and the boolean/null words.
func TestYAMLString(t *testing.T) {
	cases := map[string]string{
		"":          `""`,
		"GainA":     "GainA",
		"Card name": "Card name",
		"a:b":       `"a:b"`,
		"#tag":      `"#tag"`,
		" lead":     `" lead"`,
		"trail ":    `"trail "`,
		"true":      `"true"`,
		"Yes":       `"Yes"`,
		"off":       `"off"`,
		"null":      `"null"`,
		"tab\tin":   `"tab\tin"`,
	}
	for in, want := range cases {
		if got := yamlString(in); got != want {
			t.Errorf("yamlString(%q) = %s, want %s", in, got, want)
		}
	}
}

// TestReadYAML_GroupedFlatFormat — the pre-tree layout: groups at
// indent 4, "- label:" entries at indent 6, properties at indent 8.
// Every object property key the reader knows is exercised once.
func TestReadYAML_GroupedFlatFormat(t *testing.T) {
	in := `# acp snapshot
device:
  ip: 10.0.0.1
  port: 2071
  protocol: acp1
  protocol_version: 2
  num_slots: 2
generator: legacy
created_at: 2026-01-02T03:04:05Z
version: 1
slots:
  - slot: 1
    status: present
    walked_at: 2026-01-02T03:04:05Z
    control:
      - label: GainA
        path: [control, GainA]
        id: 7
        kind: float
        access: RW-
        unit: dB
        min: -20
        max: 20
        step: 0.5
        default: 0
        value: 1.5
      - label: Mode
        id: 8
        kind: enum
        access: RW-
        enum_items: [Off, On]
        value: 1
        value_name: On
        orphan
      - label: Count
        id: 12
        kind: uint
        value: 42
      - label: Temp
        id: 13
        kind: int
        value: -3
      - label: Flag
        id: 14
        kind: bool
        value: true
    alarm:
      - label: Fan
        id: 9
        kind: alarm
        access: R--
        alarm_priority: 2
        alarm_tag: 0x1F
        alarm_on: "Fan failed"
        alarm_off: "Fan ok"
      - label: Header
        id: 10
        kind: string
        max_len: 16
        sub_group_marker: true
        value: "\"quoted\""
      - label: "bad\q"
        id: 15
        kind: ipaddr
        value: 10.6.250.101
  - slot: 2
    identity:
      - label: Other
        id: 1
        kind: string
        value: x
`
	snap, err := ReadYAML(strings.NewReader(in))
	if err != nil {
		t.Fatalf("ReadYAML: %v", err)
	}
	if snap.Device != (DeviceInfo{IP: "10.0.0.1", Port: 2071, Protocol: "acp1", ProtocolVersion: 2, NumSlots: 2}) {
		t.Errorf("device: %+v", snap.Device)
	}
	if snap.Generator != "legacy" || !snap.CreatedAt.Equal(time.Date(2026, 1, 2, 3, 4, 5, 0, time.UTC)) {
		t.Errorf("generator/created_at: %q %v", snap.Generator, snap.CreatedAt)
	}
	if len(snap.Slots) != 2 {
		t.Fatalf("slots got %d, want 2", len(snap.Slots))
	}
	s1 := snap.Slots[0]
	if s1.Slot != 1 || s1.Status != "present" || !s1.WalkedAt.Equal(snap.CreatedAt) {
		t.Errorf("slot 1 header: %+v", s1)
	}
	if len(s1.Objects) != 8 {
		t.Fatalf("slot 1 objects got %d, want 8", len(s1.Objects))
	}
	by := map[string]consumer.Object{}
	for _, o := range s1.Objects {
		by[o.Label] = o
	}
	g := by["GainA"]
	if strings.Join(g.Path, ".") != "control.GainA" || g.Group != "control" || g.ID != 7 || g.Kind != consumer.KindFloat || g.Access != 3 || g.Unit != "dB" {
		t.Errorf("GainA: %+v", g)
	}
	if g.Min != float64(-20) || g.Max != float64(20) || g.Step != float64(0.5) || g.Def != float64(0) || g.Value.Float != 1.5 || g.Value.Kind != consumer.KindFloat {
		t.Errorf("GainA numeric: %+v", g)
	}
	m := by["Mode"]
	if m.Group != "control" || strings.Join(m.Path, ".") != "control" || len(m.EnumItems) != 2 || m.Value.Enum != 1 || m.Value.Str != "On" {
		t.Errorf("Mode: %+v", m)
	}
	if by["Count"].Value.Uint != 42 || by["Temp"].Value.Int != -3 || by["Flag"].Value.Kind != consumer.KindBool {
		t.Errorf("scalar values: %+v %+v %+v", by["Count"].Value, by["Temp"].Value, by["Flag"].Value)
	}
	f := by["Fan"]
	if f.Group != "alarm" || f.Kind != consumer.KindAlarm || f.AlarmPriority != 2 || f.AlarmTag != 0x1F || f.AlarmOnMsg != "Fan failed" || f.AlarmOffMsg != "Fan ok" {
		t.Errorf("Fan: %+v", f)
	}
	h := by["Header"]
	if h.MaxLen != 16 || !h.SubGroupMarker || h.Value.Str != `"quoted"` {
		t.Errorf("Header: %+v", h)
	}
	b := by[`bad\q`]
	if b.ID != 15 || b.Value.IPAddr != [4]byte{10, 6, 250, 101} {
		t.Errorf("a string with an invalid escape keeps its inner text: %+v", b)
	}
	if s2 := snap.Slots[1]; s2.Slot != 2 || len(s2.Objects) != 1 || s2.Objects[0].Group != "identity" || s2.Objects[0].Value.Str != "x" {
		t.Errorf("slot 2: %+v", s2)
	}
}

// TestReadYAML_Hierarchical — the tree layout the writer emits today,
// plus the reader's tolerance for a legacy "objects:" header and a
// stray property line before any node.
func TestReadYAML_Hierarchical(t *testing.T) {
	in := `device:
  ip: 10.41.40.195
  protocol: acp2
slots:
  - slot: 0
    objects:
      Loose:
        id: 3
        kind: string
        value: hi
  - slot: 1
    BOARD:
      id: 5
      Temp:
        id: 10
        kind: int
        access: R--
        value: 42
      PSU:
        "1":
          Present:
            id: 60001
            kind: enum
            access: R--
            enum_items: [no, yes]
            value: 1
            value_name: yes
`
	snap, err := ReadYAML(strings.NewReader(in))
	if err != nil {
		t.Fatalf("ReadYAML: %v", err)
	}
	if len(snap.Slots) != 2 {
		t.Fatalf("slots: %+v", snap.Slots)
	}
	s0 := snap.Slots[0]
	if len(s0.Objects) != 1 || s0.Objects[0].Label != "Loose" || strings.Join(s0.Objects[0].Path, ".") != "Loose" || s0.Objects[0].Value.Str != "hi" {
		t.Errorf("legacy objects header nests from the slot root: %+v", s0.Objects)
	}
	var got []string
	for _, o := range snap.Slots[1].Objects {
		got = append(got, strings.Join(o.Path, "."))
	}
	if want := "BOARD.Temp,BOARD.PSU,BOARD.PSU.1,BOARD.PSU.1.Present"; strings.Join(got, ",") != want {
		t.Fatalf("paths got %v, want %s", got, want)
	}
	objs := snap.Slots[1].Objects
	if objs[0].ID != 10 || objs[0].Group != "BOARD" || objs[0].Value.Int != 42 {
		t.Errorf("Temp: %+v", objs[0])
	}
	if objs[1].ID != 0 || objs[2].ID != 0 {
		t.Errorf("containers carry no properties: %+v %+v", objs[1], objs[2])
	}
	if p := objs[3]; p.ID != 60001 || p.Value.Enum != 1 || p.Value.Str != "yes" || len(p.EnumItems) != 2 {
		t.Errorf("Present: %+v", p)
	}
}

// TestReadYAML_Edges — slot entries not keyed by "slot", and the one
// scanner failure the reader can hit: a line over bufio's 64 KiB token
// limit.
func TestReadYAML_Edges(t *testing.T) {
	t.Run("slot entry keyed by another field keeps slot 0", func(t *testing.T) {
		snap, err := ReadYAML(strings.NewReader("slots:\n  - status: present\n    objects:\n"))
		if err != nil {
			t.Fatalf("ReadYAML: %v", err)
		}
		if len(snap.Slots) != 1 || snap.Slots[0].Slot != 0 {
			t.Errorf("slots: %+v", snap.Slots)
		}
	})
	t.Run("oversized line", func(t *testing.T) {
		_, err := ReadYAML(strings.NewReader("device:\n  ip: " + strings.Repeat("x", bufio.MaxScanTokenSize+1) + "\n"))
		if !errors.Is(err, bufio.ErrTooLong) || !strings.HasPrefix(err.Error(), "yaml scan:") {
			t.Errorf("got %v, want yaml scan: token too long", err)
		}
	})
}

// TestParseFlowSeq — flow sequences, bare scalars, and empties.
func TestParseFlowSeq(t *testing.T) {
	cases := []struct {
		in   string
		want string
	}{
		{"[Off, On]", "Off|On"},
		{`["a:b", c]`, "a:b|c"},
		{"[]", ""},
		{"", ""},
		{"control", "control"},
		{`"quoted one"`, "quoted one"},
	}
	for _, c := range cases {
		if got := strings.Join(parseFlowSeq(c.in), "|"); got != c.want {
			t.Errorf("parseFlowSeq(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}
