package mib

// The compiled vocabulary: every object the vendor and standard MIBs in
// this plant define, as tools/mibc wrote it. The table is data, not code
// — 74,000 rows would be a Go file nobody could review — and it is read
// once, lazily, because a `get sysDescr.0` has no business decompressing
// twelve megabytes of names it will never print.

import (
	"bufio"
	"bytes"
	"compress/gzip"
	_ "embed"
	"fmt"
	"io"
	"sort"
	"strconv"
	"strings"
	"sync"

	"dhs/internal/snmp/codec"
)

// TableHeader is the first line of a table. tools/mibc writes this
// constant and ParseTable refuses anything else, so a change to the
// column layout is a change here that the reader and the writer both see.
const TableHeader = "# dhs-snmp-mib-table v1 — GENERATED by tools/mibc, do not edit"

//go:embed tables.tsv.gz
var embedded []byte

// Enum is one named number of an INTEGER enumeration.
type Enum struct {
	Name  string
	Value int64
}

// Object is one row of the compiled table.
type Object struct {
	OID    codec.OID
	Name   string
	Module string
	// Kind is the macro that defined it: object-type, notification,
	// trap, object-identifier, and so on.
	Kind string
	// Base is the primitive the syntax comes down to, and TC the textual
	// convention it was written as, if any.
	Base, TC string
	Access   string
	Enums    []Enum
	Index    []string
}

// EnumName is the label for v, when the object enumerates one.
func (o *Object) EnumName(v int64) (string, bool) {
	for _, e := range o.Enums {
		if e.Value == v {
			return e.Name, true
		}
	}
	return "", false
}

// Table is a parsed compiled table.
//
// One OID can carry more than one row. The TT1260 and RX1290 report the
// same sysObjectID and put different objects at 34 of the same OIDs, so
// which name is right depends on the device; the rows for one OID are
// kept together, the compiler's default first, and a caller that knows
// the device passes the module it wants preferred.
type Table struct {
	objs   []Object
	byOID  map[string][]int
	byName map[string][]int
}

// Len is the number of rows.
func (t *Table) Len() int { return len(t.objs) }

// ParseTable reads a table in the layout tools/mibc writes: gzip, then
// the header line, then one tab-separated row per object —
//
//	oid  name  module  kind  base  tc  access  enums  index
//
// with enums as name=value joined by ';' and index names joined by ','.
func ParseTable(r io.Reader) (*Table, error) {
	zr, err := gzip.NewReader(r)
	if err != nil {
		return nil, fmt.Errorf("mib: table: %w", err)
	}
	sc := bufio.NewScanner(zr)
	sc.Buffer(make([]byte, 64*1024), 1<<20)
	if !sc.Scan() || sc.Text() != TableHeader {
		return nil, fmt.Errorf("mib: table: the first line is not %q", TableHeader)
	}
	t := &Table{byOID: map[string][]int{}, byName: map[string][]int{}}
	// Module names repeat on every row; one copy each.
	modules := map[string]string{}
	for line := 2; sc.Scan(); line++ {
		o, err := parseRow(sc.Text(), modules)
		if err != nil {
			return nil, fmt.Errorf("mib: table line %d: %w", line, err)
		}
		i := len(t.objs)
		t.objs = append(t.objs, o)
		key := o.OID.String()
		t.byOID[key] = append(t.byOID[key], i)
		t.byName[o.Name] = append(t.byName[o.Name], i)
	}
	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("mib: table: %w", err)
	}
	return t, nil
}

func parseRow(row string, modules map[string]string) (Object, error) {
	f := strings.Split(row, "\t")
	if len(f) != 9 {
		return Object{}, fmt.Errorf("%d columns, want 9", len(f))
	}
	oid, err := codec.ParseOID(f[0])
	if err != nil {
		return Object{}, err
	}
	mod, ok := modules[f[2]]
	if !ok {
		mod = f[2]
		modules[mod] = mod
	}
	o := Object{OID: oid, Name: f[1], Module: mod, Kind: f[3], Base: f[4], TC: f[5], Access: f[6]}
	for _, e := range splitNonEmpty(f[7], ";") {
		name, val, _ := strings.Cut(e, "=")
		n, err := strconv.ParseInt(val, 10, 64)
		if err != nil {
			return Object{}, fmt.Errorf("enumeration member %q has no number", e)
		}
		o.Enums = append(o.Enums, Enum{name, n})
	}
	o.Index = splitNonEmpty(f[8], ",")
	return o, nil
}

func splitNonEmpty(s, sep string) []string {
	if s == "" {
		return nil
	}
	return strings.Split(s, sep)
}

// pick chooses among the rows for one OID: the first from a preferred
// module, else the compiler's default.
func (t *Table) pick(rows []int, prefer []string) *Object {
	for _, m := range prefer {
		for _, i := range rows {
			if t.objs[i].Module == m {
				return &t.objs[i]
			}
		}
	}
	return &t.objs[rows[0]]
}

// Lookup finds the object o is, or the deepest one it is under, and the
// arcs left over — a column's instance index, or nothing for a scalar
// named exactly. It returns nil when no row is a prefix of o.
func (t *Table) Lookup(o codec.OID, prefer ...string) (*Object, codec.OID) {
	for n := len(o); n > 0; n-- {
		if rows, ok := t.byOID[o[:n].String()]; ok {
			return t.pick(rows, prefer), o[n:]
		}
	}
	return nil, nil
}

// Name renders o the way net-snmp does without its module prefix: the
// deepest name that covers it, then the rest of the arcs —
// iqmux42SetupSerialNumber.32774.11 — or the dotted form when nothing
// covers it.
func (t *Table) Name(o codec.OID, prefer ...string) string {
	obj, rest := t.Lookup(o, prefer...)
	if obj == nil {
		return o.String()
	}
	return withSuffix(obj.Name, rest)
}

func withSuffix(name string, rest codec.OID) string {
	if len(rest) == 0 {
		return name
	}
	return name + "." + rest.String()
}

// Resolve turns a compiled name into an OID: name, name.index, or
// MODULE::name.index where a bare name is defined at more than one OID.
func (t *Table) Resolve(s string) (codec.OID, error) {
	mod, sym, qualified := strings.Cut(s, "::")
	if !qualified {
		mod, sym = "", s
	}
	name, index, _ := strings.Cut(sym, ".")
	var hits []*Object
	seen := map[string]bool{}
	for _, i := range t.byName[name] {
		o := &t.objs[i]
		if mod != "" && o.Module != mod {
			continue
		}
		if k := o.OID.String(); !seen[k] {
			seen[k] = true
			hits = append(hits, o)
		}
	}
	switch len(hits) {
	case 0:
		return nil, fmt.Errorf("mib: %q is not a standard name, a compiled MIB name or a dotted OID", s)
	case 1:
	default:
		mods := make([]string, len(hits))
		for i, h := range hits {
			mods[i] = h.Module + "::" + name
		}
		sort.Strings(mods)
		return nil, fmt.Errorf("mib: %q is defined at %d different OIDs; write one of %s",
			name, len(hits), strings.Join(mods, ", "))
	}
	arcs, err := parseArcs(index)
	if err != nil {
		return nil, fmt.Errorf("mib: %q: %w", s, err)
	}
	return hits[0].OID.Append(arcs...), nil
}

// parseArcs reads an instance index: any number of dotted arcs,
// including none.
func parseArcs(s string) ([]uint32, error) {
	if s == "" {
		return nil, nil
	}
	parts := strings.Split(s, ".")
	out := make([]uint32, len(parts))
	for i, p := range parts {
		v, err := strconv.ParseUint(p, 10, 32)
		if err != nil {
			return nil, fmt.Errorf("index arc %q is not a number", p)
		}
		out[i] = uint32(v)
	}
	return out, nil
}

// mustLoad parses a table this binary shipped with. A table that does not
// parse is a bad commit, not a runtime condition, and deserves the same
// panic as a bad OID literal.
func mustLoad(b []byte) *Table {
	t, err := ParseTable(bytes.NewReader(b))
	if err != nil {
		panic(err)
	}
	return t
}

// Compiled is the table embedded in this binary, parsed on first use.
var Compiled = sync.OnceValue(func() *Table { return mustLoad(embedded) })
