// Command gen-rollcall-ids generates the RollCall unit-type table from the
// vendor's own ID database.
//
// A RollCall unit reports a numeric type id in its ID_STR, and that number is
// the only machine-readable statement of what a device is. Turning it into a
// product name is what makes a discovered fleet legible in a manifest, in the
// device model, and in the Wireshark Info column.
//
// The source of truth is RollCall_IDs.xml, which ships with the protocol
// library. The vendor's own genfiles.py generates rc3id.h from the same file,
// so the XML is upstream of the header rather than beside it.
//
// Usage:
//
//	go run ./tools/gen-rollcall-ids \
//	    -in internal/snell-rollcall/assets/Protocol/Source/RollCallV2/Inc/RcHeader/RollCall_IDs.xml \
//	    -out internal/snell-rollcall/codec/unit_ids.go
//
// The output is committed. Regenerate it rather than editing it by hand: a
// hand-edit would be silently lost the next time the vendor ships a new
// database.
package main

import (
	"encoding/xml"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

// database mirrors the parts of RollCall_IDs.xml we need.
//
// The file has two entity sections. RollCall holds the type ids a unit
// actually reports. Vistek is a separate legacy list that reuses a handful of
// the same numbers for different products, and the vendor's own generator
// ignores it when building the header, so we do too.
type database struct {
	Categories struct {
		Category []struct {
			ID   int    `xml:"ID,attr"`
			Name string `xml:"Name,attr"`
		} `xml:"Category"`
	} `xml:"Categories"`

	RollCall struct {
		TypeID []typeID `xml:"TypeID"`
	} `xml:"RollCall"`

	Vistek struct {
		TypeID []typeID `xml:"TypeID"`
	} `xml:"Vistek"`
}

type typeID struct {
	ID          int    `xml:"ID,attr"`
	Enum        string `xml:"ENUM,attr"`
	Name        string `xml:"Name,attr"`
	Description string `xml:"Description,attr"`
	Category    int    `xml:"Category,attr"`
}

func main() {
	in := flag.String("in", "", "path to RollCall_IDs.xml")
	out := flag.String("out", "", "path to the generated Go file")
	pkg := flag.String("package", "codec", "package name for the generated file")
	flag.Parse()

	if *in == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "gen-rollcall-ids: -in and -out are required")
		os.Exit(2)
	}

	raw, err := os.ReadFile(*in)
	if err != nil {
		fail(err)
	}

	var db database
	if err := xml.Unmarshal(raw, &db); err != nil {
		fail(fmt.Errorf("parse %s: %w", *in, err))
	}

	src, n, collisions, err := generate(&db, *pkg)
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		fail(err)
	}

	fmt.Printf("gen-rollcall-ids: %d unit types -> %s\n", n, *out)
	if len(collisions) > 0 {
		fmt.Printf("gen-rollcall-ids: %d ids also appear in the Vistek section and were "+
			"taken from RollCall, matching the vendor generator: %v\n",
			len(collisions), collisions)
	}
}

func generate(db *database, pkg string) (src []byte, count int, collisions []int, err error) {
	categories := map[int]string{}
	for _, c := range db.Categories.Category {
		categories[c.ID] = c.Name
	}

	seen := map[int]bool{}
	types := make([]typeID, 0, len(db.RollCall.TypeID))
	for _, t := range db.RollCall.TypeID {
		if t.ID < 0 || t.ID > 0xFFFF {
			return nil, 0, nil, fmt.Errorf("type id %d does not fit the 16-bit field", t.ID)
		}
		if seen[t.ID] {
			return nil, 0, nil, fmt.Errorf("type id %d appears twice in the RollCall section", t.ID)
		}
		seen[t.ID] = true
		types = append(types, t)
	}
	for _, t := range db.Vistek.TypeID {
		if seen[t.ID] {
			collisions = append(collisions, t.ID)
		}
	}
	sort.Ints(collisions)

	sort.Slice(types, func(i, j int) bool { return types[i].ID < types[j].ID })

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by tools/gen-rollcall-ids. DO NOT EDIT.
//
// Source: RollCall_IDs.xml, the vendor's ID database, from which the vendor's
// own genfiles.py also generates rc3id.h.

package %s

// UnitCategory is the product family a type id belongs to.
type UnitCategory uint8

// The categories the vendor database defines.
const (
	CategoryUnknown UnitCategory = 0
`, pkg)

	catIDs := make([]int, 0, len(categories))
	for id := range categories {
		catIDs = append(catIDs, id)
	}
	sort.Ints(catIDs)
	for _, id := range catIDs {
		fmt.Fprintf(&b, "\t%s UnitCategory = %d\n", categoryConst(categories[id]), id)
	}
	b.WriteString(")\n\n")

	b.WriteString("var unitCategoryNames = map[UnitCategory]string{\n")
	b.WriteString("\tCategoryUnknown: \"unknown\",\n")
	for _, id := range catIDs {
		fmt.Fprintf(&b, "\t%s: %q,\n", categoryConst(categories[id]), categories[id])
	}
	b.WriteString("}\n\n")

	b.WriteString(`// String returns the vendor's category name.
func (c UnitCategory) String() string {
	if n, ok := unitCategoryNames[c]; ok {
		return n
	}
	return "category(" + itoa(uint16(c)) + ")"
}

// UnitType describes one RollCall unit-type id.
type UnitType struct {
	ID          uint16
	Enum        string // the vendor's own constant, e.g. "ID_SIRIUS_830"
	Name        string // the short product name shown in vendor tools
	Description string
	Category    UnitCategory
}

// unitTypes is sorted by ID so lookups can binary-search it. A sorted array
// costs nothing at start-up, unlike a map literal of this size, which matters
// for a connector meant to stay small.
var unitTypes = [...]UnitType{
`)

	for _, t := range types {
		fmt.Fprintf(&b, "\t{%d, %q, %q, %q, %d},\n",
			t.ID, t.Enum, t.Name, t.Description, t.Category)
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, 0, nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, len(types), collisions, nil
}

// categoryConst turns a category name into a Go constant name.
func categoryConst(name string) string {
	var b strings.Builder
	b.WriteString("Category")
	upper := true
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			if upper {
				b.WriteString(strings.ToUpper(string(r)))
				upper = false
			} else {
				b.WriteRune(r)
			}
		default:
			upper = true
		}
	}
	return b.String()
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gen-rollcall-ids:", err)
	os.Exit(1)
}
