package main

// The generator's contract: the reference on stdout and nothing else,
// diagnostics on stderr, and an exit code that tells a failed
// invocation apart from a verb that answers -h with a non-zero exit.

import (
	"bytes"
	"errors"
	"os"
	"os/exec"
	"strings"
	"testing"
)

// exec runs the generator and returns its exit code and both streams.
func execGen(t *testing.T, argv ...string) (int, string, string) {
	t.Helper()
	var out, errs bytes.Buffer
	code := run(argv, &out, &errs)
	return code, out.String(), errs.String()
}

// useHelp answers every matrix entry with a fixed body.
func useHelp(t *testing.T, f func(bin string, argv []string) ([]byte, error)) {
	t.Helper()
	prev := helpOf
	helpOf = f
	t.Cleanup(func() { helpOf = prev })
}

// The whole matrix is rendered, each section carrying the argv that
// produced it — the page's claim is that what -h prints IS what it
// shows, so the invocation has to be on the page next to the output.
func TestReferenceRendersEveryVerb(t *testing.T) {
	var asked [][]string
	useHelp(t, func(bin string, argv []string) ([]byte, error) {
		asked = append(asked, argv)
		return []byte("usage: " + strings.Join(argv, " ")), nil
	})

	code, out, errs := execGen(t, "-dhs", "/path/to/dhs")
	if code != 0 {
		t.Fatalf("exit = %d (%s)", code, errs)
	}
	if errs != "" {
		t.Errorf("the reference goes to stdout alone: %q", errs)
	}
	if len(asked) != len(matrix) {
		t.Fatalf("asked for %d verbs, want the whole matrix (%d)", len(asked), len(matrix))
	}
	for _, e := range matrix {
		if !strings.Contains(out, "## "+e.title+"\n") {
			t.Errorf("no section for %q", e.title)
		}
		if !strings.Contains(out, "`dhs "+strings.Join(e.argv, " ")+"`") {
			t.Errorf("section %q does not show the argv that produced it", e.title)
		}
	}
	if !strings.Contains(out, "GENERATED by tools/gencli") {
		t.Error("the page must say it is generated, or somebody will edit it")
	}
}

// The contents list links to every section, and the anchors are the
// ones GitHub will mint from the headings — a table of contents whose
// links do not land is worse than none.
func TestContentsLinksMatchTheHeadings(t *testing.T) {
	useHelp(t, func(string, []string) ([]byte, error) { return []byte("help"), nil })

	_, out, _ := execGen(t, "-dhs", "/path/to/dhs")
	for _, e := range matrix {
		link := "- [" + e.title + "](#" + anchor(e.title) + ")"
		if !strings.Contains(out, link) {
			t.Errorf("missing contents entry %q", link)
		}
	}
}

// A verb that answers -h with a non-zero exit is not a failure: several
// do exactly that through flag.ErrHelp while printing the text this
// page exists to show.
func TestAVerbThatExitsNonZeroIsStillDocumented(t *testing.T) {
	useHelp(t, func(bin string, argv []string) ([]byte, error) {
		// What exec reports for a command that ran and exited 2.
		return []byte("usage: dhs " + strings.Join(argv, " ")), nil
	})

	if code, _, errs := execGen(t, "-dhs", "/path/to/dhs"); code != 0 {
		t.Fatalf("exit = %d (%s), want the page written", code, errs)
	}
}

// A binary that cannot be started is a failure, because the page it
// would produce is a wall of empty code blocks that CI then diffs
// against the real one and reports every verb as changed.
func TestABinaryThatWillNotStartIsRefused(t *testing.T) {
	useHelp(t, func(string, []string) ([]byte, error) {
		return nil, errors.New("file does not exist")
	})

	code, out, errs := execGen(t, "-dhs", "/no/such/binary")
	if code != 2 {
		t.Fatalf("exit = %d, want 2", code)
	}
	if out != "" {
		t.Errorf("nothing must be written when the page cannot be built: %q", out)
	}
	if !strings.Contains(errs, "/no/such/binary") {
		t.Errorf("the refusal must name the binary: %q", errs)
	}
}

// Usage errors are exit 2 and say what is missing.
func TestUsageErrors(t *testing.T) {
	if code, _, errs := execGen(t); code != 2 || !strings.Contains(errs, "-dhs") {
		t.Errorf("no -dhs = %d %q", code, errs)
	}
	if code, _, _ := execGen(t, "-nonsense"); code != 2 {
		t.Errorf("an unknown flag = %d, want 2", code)
	}
}

// The anchors are GitHub's: lowercase, spaces and hyphens to hyphens,
// everything else dropped. A heading with a colon or brackets in it
// still has to link.
func TestAnchor(t *testing.T) {
	for _, tc := range []struct{ in, want string }{
		{"dhs (root)", "dhs-root"},
		{"NMOS controller: connect (IS-05)", "nmos-controller-connect-is-05"},
		{"probel-sw08p", "probel-sw08p"},
		{"list-commands", "list-commands"},
		{"Consumer verbs", "consumer-verbs"},
	} {
		if got := anchor(tc.in); got != tc.want {
			t.Errorf("anchor(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

// helpOf reports a command that ran and one that could not be started
// differently, which is the whole basis of the exit code above.
func TestHelpOfTellsTheTwoFailuresApart(t *testing.T) {
	// A command that does not exist cannot be started.
	if _, err := helpOf("no-such-binary-anywhere", []string{"--help"}); err == nil {
		t.Error("a binary that is not there must be reported")
	}

	// One that runs and exits non-zero is not an error here. `go` is
	// on PATH wherever these tests run, and `go nonsense-verb` exits
	// non-zero with its usage on stderr.
	out, err := helpOf(goBinary(t), []string{"nonsense-verb"})
	if err != nil {
		t.Errorf("a non-zero exit must not be an error: %v", err)
	}
	if len(out) == 0 {
		t.Error("what the command printed must come back")
	}
}

// goBinary is the go tool, which is on PATH for any machine running
// these tests.
func goBinary(t *testing.T) string {
	t.Helper()
	path, err := exec.LookPath("go")
	if err != nil {
		t.Skipf("go is not on PATH: %v", err)
	}
	return path
}

// main is the entry point CI calls, so it is exercised as one.
func TestMainWiring(t *testing.T) {
	useHelp(t, func(string, []string) ([]byte, error) { return []byte("help"), nil })

	prevArgs, prevExit := os.Args, osExit
	var got int
	os.Args = []string{"gencli"} // no -dhs: the usage path, which writes no page
	osExit = func(code int) { got = code }
	t.Cleanup(func() { os.Args, osExit = prevArgs, prevExit })

	main()

	if got != 2 {
		t.Errorf("main exited %d, want 2", got)
	}
}
