// Command gencli regenerates docs/cli.md — the complete `dhs` verb
// reference — by running the REAL binary's help output for every
// entry of the verb matrix below. The document therefore cannot drift
// from the code: what -h prints IS what the page shows.
//
//	go run ./tools/gencli -dhs <path-to-dhs-binary> > docs/cli.md
//
// CI regenerates and diffs it; a verb added without updating the
// matrix here fails the freshness check the moment its help text
// differs from nothing.
package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// helpEntry is one section of the reference: a title and the argv
// whose output (stdout+stderr — help goes to either) fills it.
type helpEntry struct {
	title string
	argv  []string
}

// The matrix. Grouped the way an operator thinks: the roles first,
// then per-protocol surfaces, then the cross-cutting tools.
var matrix = []helpEntry{
	{"dhs (root)", []string{"--help"}},
	{"Consumer verbs", []string{"consumer", "--help"}},
	{"Producer verbs", []string{"producer", "--help"}},

	// AMWA NMOS — the three roles.
	{"NMOS node (producer)", []string{"producer", "nmos", "serve", "--help"}},
	{"NMOS registry", []string{"registry", "nmos", "serve", "--help"}},
	{"NMOS controller: walk", []string{"consumer", "nmos", "walk", "--help"}},
	{"NMOS controller: watch", []string{"consumer", "nmos", "watch", "--help"}},
	{"NMOS controller: connect (IS-05)", []string{"consumer", "nmos", "connect", "--help"}},
	{"NMOS controller: set", []string{"consumer", "nmos", "set", "--help"}},
	{"NMOS controller: events (IS-07)", []string{"consumer", "nmos", "events", "--help"}},

	// The generic consumer verb set (shape shared by acp1/acp2/emberplus).
	{"consumer info", []string{"consumer", "acp1", "info", "--help"}},
	{"consumer walk", []string{"consumer", "acp1", "walk", "--help"}},
	{"consumer get", []string{"consumer", "acp1", "get", "--help"}},
	{"consumer set", []string{"consumer", "acp1", "set", "--help"}},
	{"consumer watch", []string{"consumer", "acp1", "watch", "--help"}},
	{"consumer export", []string{"consumer", "acp1", "export", "--help"}},
	{"consumer import", []string{"consumer", "acp1", "import", "--help"}},
	{"consumer matrix", []string{"consumer", "emberplus", "matrix", "--help"}},
	{"consumer invoke", []string{"consumer", "emberplus", "invoke", "--help"}},

	// Per-protocol surfaces with their own verb sets.
	{"probel-sw08p", []string{"consumer", "probel-sw08p", "--help"}},
	{"probel-sw02p", []string{"consumer", "probel-sw02p", "--help"}},
	{"cerebrum-nb", []string{"consumer", "cerebrum-nb", "--help"}},
	{"osc", []string{"consumer", "osc", "--help"}},
	{"tsl", []string{"consumer", "tsl", "--help"}},

	// Cross-cutting tools.
	{"list-commands", []string{"list-commands", "--help"}},
	{"metrics", []string{"metrics", "--help"}},
}

func main() {
	dhs := flag.String("dhs", "", "path to the dhs binary (required)")
	flag.Parse()
	if *dhs == "" {
		fmt.Fprintln(os.Stderr, "gencli: -dhs <binary> is required")
		os.Exit(2)
	}

	var b strings.Builder
	b.WriteString("# dhs CLI reference\n\n")
	b.WriteString("<!-- GENERATED by tools/gencli — do not edit. Regenerate with:\n")
	b.WriteString("     go build -o /tmp/dhs ./cmd/dhs && go run ./tools/gencli -dhs /tmp/dhs > docs/cli.md -->\n\n")
	b.WriteString("Every verb accepts `--settings <file.yaml>` (or `DHS_SETTINGS`): a FLAT\n")
	b.WriteString("YAML of `flag-name: value` defaults, names exactly as `-h` prints them.\n")
	b.WriteString("Precedence: explicit flags > settings file > built-in defaults. Keys that\n")
	b.WriteString("belong to other verbs are ignored, so one file serves a deployment —\n")
	b.WriteString("Ansible templates render the same shape.\n\n")
	b.WriteString("## Contents\n\n")
	for _, e := range matrix {
		fmt.Fprintf(&b, "- [%s](#%s)\n", e.title, anchor(e.title))
	}
	b.WriteString("\n")

	for _, e := range matrix {
		out, _ := exec.Command(*dhs, e.argv...).CombinedOutput() //nolint:gosec // argv is the fixed matrix above
		fmt.Fprintf(&b, "## %s\n\n`dhs %s`\n\n```text\n%s\n```\n\n",
			e.title, strings.Join(e.argv, " "), strings.TrimRight(string(out), "\n"))
	}
	fmt.Print(b.String())
}

// anchor renders a GitHub-style heading anchor.
func anchor(title string) string {
	s := strings.ToLower(title)
	var out []rune
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z' || r >= '0' && r <= '9':
			out = append(out, r)
		case r == ' ' || r == '-':
			out = append(out, '-')
		}
	}
	return string(out)
}
