// Package connection is the IS-05 Connection Management client — the only
// NMOS-standard way to change what a Sender emits.
//
// A controller never edits an SDP: the SDP is generated by the Sender from its
// transport parameters. Setting `destination_ip` / `destination_port` on the
// staged endpoint and activating makes the node re-emit it. Nothing else in
// the SDP (rtpmap, fmtp, ts-refclk, the label in `s=`) is reachable through
// IS-05 — those come from the node's own configuration.
package connection

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strings"
	"time"

	"dhs/internal/amwa/codec/is05"
)

// Client speaks IS-05 to one node.
//
// Base is the connection API root advertised in the Device's `controls` array
// under `urn:x-nmos:control:sr-ctrl/...`, e.g.
// http://10.44.72.18:3000/x-nmos/connection/v1.1
type Client struct {
	Base string
	HTTP *http.Client
}

// NewClient builds a Client for the given connection API base URL.
func NewClient(base string) (*Client, error) {
	base = strings.TrimSpace(base)
	if base == "" {
		return nil, errors.New("connection: base URL is required")
	}
	if !strings.HasPrefix(base, "http://") && !strings.HasPrefix(base, "https://") {
		return nil, fmt.Errorf("connection: base URL %q needs a scheme", base)
	}
	return &Client{
		Base: strings.TrimRight(base, "/"),
		HTTP: &http.Client{Timeout: 15 * time.Second},
	}, nil
}

// Side selects senders or receivers.
type Side string

// The two IS-05 single endpoints.
const (
	Senders   Side = "senders"
	Receivers Side = "receivers"
)

func (c *Client) single(side Side, id, leaf string) string {
	return fmt.Sprintf("%s/single/%s/%s/%s", c.Base, side, id, leaf)
}

// Leg is one entry of `transport_params` — one SMPTE 2022-7 leg, in the same
// order as the SDP's m= sections.
//
// Every field is a pointer so that "not set" and "set to zero" stay
// distinguishable: IS-05 PATCH is a partial update, and sending
// `"destination_port": 0` would ask the node to use port 0.
type Leg struct {
	DestinationIP   *string `json:"destination_ip,omitempty"`
	DestinationPort *int    `json:"destination_port,omitempty"`
	SourceIP        *string `json:"source_ip,omitempty"`
	SourcePort      *int    `json:"source_port,omitempty"`
	RTPEnabled      *bool   `json:"rtp_enabled,omitempty"`
}

// Patch is the body sent to a staged endpoint. Omitted fields are left alone
// by the node, which is what makes a targeted mcast/port change safe.
type Patch struct {
	MasterEnable    *bool               `json:"master_enable,omitempty"`
	TransportParams []Leg               `json:"transport_params,omitempty"`
	Activation      *is05.Activation    `json:"activation,omitempty"`
	TransportFile   *is05.TransportFile `json:"transport_file,omitempty"`
	ReceiverID      *string             `json:"receiver_id,omitempty"`
	SenderID        *string             `json:"sender_id,omitempty"`
}

// SetDestination builds the patch this whole package exists for: point a
// sender's legs at new multicast addresses and ports, and activate.
//
// legs must carry one entry per 2022-7 leg IN SDP ORDER — a two-leg sender
// patched with one entry leaves the second leg untouched, which produces a
// half-moved stream rather than an error.
func SetDestination(legs []Leg, mode is05.ActivationMode) Patch {
	enable := true
	p := Patch{MasterEnable: &enable, TransportParams: legs}
	if mode != is05.ActivationModeNone {
		p.Activation = &is05.Activation{Mode: mode}
	}
	return p
}

// PatchStaged applies p to the staged endpoint and returns what the node
// staged in response.
func (c *Client) PatchStaged(ctx context.Context, side Side, id string, p Patch) (*is05.StagedSender, error) {
	if id == "" {
		return nil, errors.New("connection: resource id is required")
	}
	if p.Activation != nil && !is05.IsValidActivationMode(p.Activation.Mode) {
		return nil, fmt.Errorf("connection: invalid activation mode %q", p.Activation.Mode)
	}

	body, err := json.Marshal(p)
	if err != nil {
		return nil, fmt.Errorf("connection: encode patch: %w", err)
	}
	url := c.single(side, id, "staged")
	req, err := http.NewRequestWithContext(ctx, http.MethodPatch, url, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("connection: build request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTP.Do(req)
	if err != nil {
		return nil, fmt.Errorf("connection: PATCH %s: %w", url, err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("connection: PATCH %s: unexpected status %d", url, resp.StatusCode)
	}
	var out is05.StagedSender
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return nil, fmt.Errorf("connection: decode staged response: %w", err)
	}
	return &out, nil
}

// Staged reads the staged endpoint.
func (c *Client) Staged(ctx context.Context, side Side, id string) (*is05.StagedSender, error) {
	return c.getStaged(ctx, c.single(side, id, "staged"))
}

// Active reads the active endpoint — what the node is doing right now.
func (c *Client) Active(ctx context.Context, side Side, id string) (*is05.StagedSender, error) {
	return c.getStaged(ctx, c.single(side, id, "active"))
}

func (c *Client) getStaged(ctx context.Context, url string) (*is05.StagedSender, error) {
	raw, err := c.getRaw(ctx, url)
	if err != nil {
		return nil, err
	}
	var out is05.StagedSender
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("connection: decode %s: %w", url, err)
	}
	return &out, nil
}

// Constraints reads the per-leg constraints — which transport_params a caller
// may set, and within what ranges. Check before patching rather than
// discovering a rejection.
func (c *Client) Constraints(ctx context.Context, side Side, id string) ([]map[string]any, error) {
	raw, err := c.getRaw(ctx, c.single(side, id, "constraints"))
	if err != nil {
		return nil, err
	}
	var out []map[string]any
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("connection: decode constraints: %w", err)
	}
	return out, nil
}

// TransportFile fetches a sender's SDP. Read-only: no published NMOS spec
// allows writing a sender's transport file.
func (c *Client) TransportFile(ctx context.Context, id string) ([]byte, error) {
	return c.getRaw(ctx, c.single(Senders, id, "transportfile"))
}

func (c *Client) getRaw(ctx context.Context, url string) ([]byte, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, fmt.Errorf("connection: build request: %w", err)
	}
	resp, err := c.HTTP.Do(req)
	if err != nil {
		return nil, fmt.Errorf("connection: GET %s: %w", url, err)
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("connection: GET %s: unexpected status %d", url, resp.StatusCode)
	}
	buf := new(bytes.Buffer)
	if _, err := buf.ReadFrom(resp.Body); err != nil {
		return nil, fmt.Errorf("connection: read %s: %w", url, err)
	}
	return buf.Bytes(), nil
}

// StrPtr and IntPtr are helpers for building a Leg without local variables.
func StrPtr(s string) *string { return &s }

// IntPtr returns a pointer to i.
func IntPtr(i int) *int { return &i }

// BoolPtr returns a pointer to b.
func BoolPtr(b bool) *bool { return &b }
